/* =========================================================
   Base de datos nutricional
   Dietas: med (Mediterránea), dash (DASH), flex (Flexitariana), mind (MIND)
   Beneficios: presion, corazon, diabetes, cerebro, peso, colesterol, intestino
   Proteína (p): pescado, ave, carne, legumbre, huevo, lacteo, veg
   Contiene (al): gluten, lacteo, pescado, huevo, frutos_secos
   Categorías de compra: verde, fruta, grano, legumbre, prot, lacteo, grasa, sabor, despensa
   Cantidades: por persona y ración
   ========================================================= */

const CATEGORIAS = {
  verde: { nombre: "🥬 Verduras y hortalizas", orden: 1 },
  fruta: { nombre: "🍎 Frutas", orden: 2 },
  grano: { nombre: "🌾 Granos integrales", orden: 3 },
  legumbre: { nombre: "🫘 Legumbres", orden: 4 },
  prot: { nombre: "🐟 Pescado, ave y huevos", orden: 5 },
  lacteo: { nombre: "🥛 Lácteos", orden: 6 },
  grasa: { nombre: "🥑 Grasas buenas y frutos secos", orden: 7 },
  sabor: { nombre: "🌿 Hierbas, especias y ácidos", orden: 8 },
  despensa: { nombre: "🏺 Despensa", orden: 9 },
};

const DIETAS = {
  med: { nombre: "Mediterránea", color: "#2e7d52" },
  dash: { nombre: "DASH", color: "#2563a8" },
  flex: { nombre: "Flexitariana", color: "#b0691c" },
  mind: { nombre: "MIND", color: "#7b4fa6" },
};

const BENEFICIOS = {
  presion: "Presión arterial",
  corazon: "Salud cardiovascular",
  diabetes: "Control glucémico",
  cerebro: "Salud cognitiva",
  peso: "Control de peso",
  colesterol: "Colesterol",
  intestino: "Salud intestinal",
};

/* ---------------- RECETAS ---------------- */
/* t: tipos de comida donde encaja — des, com, cen, snk */
const RECETAS = [
  /* ===== DESAYUNOS ===== */
  { id: "d01", n: "Porridge de avena con arándanos y nueces", t: ["des"], d: ["mind", "dash"], p: ["veg"], al: ["frutos_secos"],
    b: ["cerebro", "colesterol", "corazon"],
    ing: [["copos de avena", "grano", "50 g"], ["arándanos", "fruta", "80 g"], ["nueces", "grasa", "20 g"], ["canela", "sabor", "1 pizca"], ["bebida vegetal o leche", "lacteo", "200 ml"]],
    coccion: "Cocer la avena 5 min a fuego suave removiendo; coronar con arándanos, nueces y canela.",
    tip: "Usa avena certificada sin gluten si eres celíaco." },
  { id: "d02", n: "Yogur griego con fresas, chía y miel", t: ["des"], d: ["med", "dash"], p: ["lacteo"], al: ["lacteo"],
    b: ["intestino", "corazon"],
    ing: [["yogur griego natural", "lacteo", "150 g"], ["fresas", "fruta", "100 g"], ["semillas de chía", "grasa", "1 cda"], ["miel", "despensa", "1 cdta"]],
    coccion: "Sin cocción: montar en capas y dejar reposar 5 min para que la chía hidrate.",
    tip: "El yogur natural sin azúcar es el probiótico más barato que existe." },
  { id: "d03", n: "Tostada integral con tomate rallado y AOVE", t: ["des"], d: ["med"], p: ["veg"], al: ["gluten"],
    b: ["corazon", "presion"],
    ing: [["pan integral de masa madre", "grano", "2 rebanadas"], ["tomate maduro", "verde", "1 ud"], ["aceite de oliva virgen extra", "grasa", "1 cda"], ["orégano", "sabor", "al gusto"]],
    coccion: "Tostar el pan, rallar el tomate encima y regar con AOVE.",
    tip: "El desayuno más mediterráneo posible: licopeno + grasa buena." },
  { id: "d04", n: "Tostada de aguacate con huevo escalfado", t: ["des"], d: ["flex", "mind"], p: ["huevo"], al: ["gluten", "huevo"],
    b: ["cerebro", "peso"],
    ing: [["pan integral", "grano", "1 rebanada"], ["aguacate", "grasa", "½ ud"], ["huevo", "prot", "1 ud"], ["limón", "sabor", "unas gotas"], ["pimienta negra", "sabor", "al gusto"]],
    coccion: "Escalfar el huevo 3 min en agua con un chorrito de vinagre; chafar el aguacate con limón sobre la tostada.",
    tip: "Grasa insaturada + proteína = saciedad hasta la comida." },
  { id: "d05", n: "Revuelto de espinacas y champiñones", t: ["des"], d: ["mind", "flex"], p: ["huevo"], al: ["huevo"],
    b: ["cerebro", "peso"],
    ing: [["huevos", "prot", "2 ud"], ["espinacas frescas", "verde", "80 g"], ["champiñones", "verde", "80 g"], ["ajo", "sabor", "1 diente"], ["aceite de oliva virgen extra", "grasa", "1 cdta"]],
    coccion: "Saltear ajo, champiñón y espinaca 3 min; añadir huevo batido fuera del fuego fuerte, cuajar cremoso.",
    tip: "Hoja verde en el desayuno: la ración MIND más fácil de cumplir." },
  { id: "d06", n: "Kéfir con plátano, lino molido y canela", t: ["des"], d: ["dash", "med"], p: ["lacteo"], al: ["lacteo"],
    b: ["intestino", "presion"],
    ing: [["kéfir", "lacteo", "200 ml"], ["plátano", "fruta", "1 ud"], ["lino molido", "grasa", "1 cda"], ["canela", "sabor", "1 pizca"]],
    coccion: "Sin cocción: trocear el plátano y mezclar.",
    tip: "El potasio del plátano es aliado directo de la presión arterial (DASH)." },
  { id: "d07", n: "Overnight oats de manzana y canela", t: ["des"], d: ["dash", "flex"], p: ["veg"], al: [],
    b: ["colesterol", "diabetes"],
    ing: [["copos de avena", "grano", "50 g"], ["manzana", "fruta", "1 ud"], ["bebida vegetal sin azúcar", "despensa", "150 ml"], ["semillas de chía", "grasa", "1 cdta"], ["canela", "sabor", "1 pizca"]],
    coccion: "Mezclar todo la noche anterior con la manzana rallada; nevera y listo al despertar.",
    tip: "Los beta-glucanos de la avena reducen el colesterol LDL — evidencia sólida." },
  { id: "d08", n: "Tortilla francesa de hierbas con tomate aliñado", t: ["des"], d: ["med"], p: ["huevo"], al: ["huevo"],
    b: ["peso"],
    ing: [["huevos", "prot", "2 ud"], ["perejil y cebollino", "sabor", "1 puñado"], ["tomate", "verde", "1 ud"], ["aceite de oliva virgen extra", "grasa", "1 cdta"]],
    coccion: "Batir huevos con hierbas picadas, cuajar a fuego medio; tomate en gajos con AOVE y orégano.",
    tip: "Las hierbas frescas dan sabor sin una pizca de sal." },
  { id: "d09", n: "Smoothie verde de espinaca, plátano y kiwi", t: ["des"], d: ["flex", "mind"], p: ["veg"], al: [],
    b: ["cerebro", "intestino"],
    ing: [["espinacas frescas", "verde", "50 g"], ["plátano", "fruta", "1 ud"], ["kiwi", "fruta", "1 ud"], ["bebida vegetal sin azúcar", "despensa", "200 ml"], ["lino molido", "grasa", "1 cdta"]],
    coccion: "Batir todo 1 min. Beber al momento para no perder vitamina C.",
    tip: "Batido, no zumo: la fruta entera conserva toda su fibra." },
  { id: "d10", n: "Requesón con melocotón y almendras", t: ["des"], d: ["med", "dash"], p: ["lacteo"], al: ["lacteo", "frutos_secos"],
    b: ["presion", "peso"],
    ing: [["requesón", "lacteo", "150 g"], ["melocotón", "fruta", "1 ud"], ["almendras", "grasa", "15 g"], ["miel", "despensa", "1 cdta"]],
    coccion: "Sin cocción: montar y listo.",
    tip: "Proteína láctea + fruta: desayuno DASH de manual." },

  /* ===== PLATOS PRINCIPALES — LEGUMBRE ===== */
  { id: "m01", n: "Lentejas estofadas con verduras y pimentón", t: ["com"], d: ["med", "dash"], p: ["legumbre"], al: [],
    b: ["presion", "corazon", "diabetes", "colesterol"],
    ing: [["lentejas pardinas", "legumbre", "80 g en seco"], ["zanahoria", "verde", "1 ud"], ["cebolla", "sabor", "½ ud"], ["ajo", "sabor", "2 dientes"], ["tomate triturado", "despensa", "100 g"], ["pimentón dulce", "sabor", "1 cdta"], ["laurel", "sabor", "1 hoja"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Sofrito lento de cebolla, ajo y tomate 15 min; añadir lentejas, verduras, pimentón y agua; guisar 35-40 min a fuego suave.",
    tip: "Añade unas gotas de limón al servir: triplica la absorción del hierro." },
  { id: "m02", n: "Garbanzos con espinacas al comino", t: ["com", "cen"], d: ["med", "flex", "mind"], p: ["legumbre"], al: [],
    b: ["cerebro", "diabetes", "intestino"],
    ing: [["garbanzos cocidos", "legumbre", "200 g"], ["espinacas", "verde", "150 g"], ["ajo", "sabor", "2 dientes"], ["comino", "sabor", "1 cdta"], ["pimentón ahumado", "sabor", "½ cdta"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Dorar ajo laminado, añadir especias, garbanzos y espinacas; saltear 5 min hasta que la hoja caiga.",
    tip: "Plato andalusí clásico: legumbre + hoja verde en 10 minutos." },
  { id: "m03", n: "Curry de garbanzos con tomate y espinacas", t: ["com"], d: ["flex"], p: ["legumbre"], al: [],
    b: ["diabetes", "cerebro", "peso"],
    ing: [["garbanzos cocidos", "legumbre", "200 g"], ["tomate triturado", "despensa", "200 g"], ["espinacas", "verde", "100 g"], ["cebolla", "sabor", "½ ud"], ["cúrcuma", "sabor", "1 cdta"], ["jengibre", "sabor", "1 trozo"], ["pimienta negra", "sabor", "al gusto"], ["arroz integral", "grano", "60 g en seco"]],
    coccion: "Sofreír cebolla y jengibre, añadir especias 30 s, tomate 10 min, garbanzos y espinacas 5 min. Servir con arroz integral hervido.",
    tip: "La pimienta negra multiplica ×20 la absorción de la curcumina." },
  { id: "m04", n: "Ensalada de alubias blancas con atún y pimiento", t: ["com", "cen"], d: ["med"], p: ["legumbre", "pescado"], al: ["pescado"],
    b: ["corazon", "peso"],
    ing: [["alubias blancas cocidas", "legumbre", "180 g"], ["atún en conserva al natural", "prot", "80 g"], ["pimiento rojo", "verde", "½ ud"], ["cebolla morada", "sabor", "¼ ud"], ["perejil", "sabor", "1 puñado"], ["aceite de oliva virgen extra", "grasa", "1 cda"], ["vinagre de Jerez", "sabor", "1 cdta"]],
    coccion: "Sin cocción: mezclar y aliñar con vinagreta. Mejor tras 15 min de reposo.",
    tip: "Legumbre + pescado en un plato frío: cena de verano perfecta." },
  { id: "m05", n: "Chili de alubias rojas con arroz integral", t: ["com"], d: ["flex", "dash"], p: ["legumbre"], al: [],
    b: ["presion", "colesterol", "peso"],
    ing: [["alubias rojas cocidas", "legumbre", "200 g"], ["tomate triturado", "despensa", "200 g"], ["pimiento verde", "verde", "½ ud"], ["cebolla", "sabor", "½ ud"], ["maíz dulce", "verde", "50 g"], ["comino", "sabor", "1 cdta"], ["pimentón ahumado", "sabor", "1 cdta"], ["arroz integral", "grano", "60 g en seco"]],
    coccion: "Sofreír verduras, añadir especias, tomate y alubias; guisar 15 min. Servir sobre arroz integral.",
    tip: "Sin sal añadida: el ahumado del pimentón hace todo el trabajo (DASH)." },
  { id: "m06", n: "Salteado de tofu, brócoli y sésamo", t: ["cen"], d: ["flex"], p: ["legumbre"], al: [],
    b: ["peso", "corazon"],
    ing: [["tofu firme", "legumbre", "150 g"], ["brócoli", "verde", "200 g"], ["zanahoria", "verde", "1 ud"], ["ajo", "sabor", "1 diente"], ["jengibre", "sabor", "1 trozo"], ["semillas de sésamo", "grasa", "1 cda"], ["salsa de soja baja en sal", "despensa", "1 cda"]],
    coccion: "Wok a fuego fuerte: dorar el tofu en dados, retirar; saltear verduras 4 min, devolver el tofu, sazonar y sembrar sésamo.",
    tip: "Prensa el tofu 15 min antes: queda dorado, no aguado." },
  { id: "m07", n: "Hamburguesa de alubia negra con ensalada completa", t: ["com", "cen"], d: ["flex"], p: ["legumbre"], al: ["huevo"],
    b: ["peso", "corazon"],
    ing: [["alubias negras cocidas", "legumbre", "180 g"], ["copos de avena", "grano", "3 cda"], ["huevo", "prot", "1 ud"], ["comino", "sabor", "1 cdta"], ["mezcla de hojas verdes", "verde", "100 g"], ["tomate", "verde", "1 ud"], ["aguacate", "grasa", "½ ud"]],
    coccion: "Chafar alubias con avena, huevo y comino; formar y dorar 4 min por cara a la plancha. Acompañar de ensalada con aguacate.",
    tip: "La avena liga la hamburguesa sin pan rallado refinado." },
  { id: "m08", n: "Buddha bowl de quinoa, verduras asadas y tahini", t: ["com", "cen"], d: ["flex", "med"], p: ["legumbre"], al: [],
    b: ["intestino", "peso", "diabetes"],
    ing: [["quinoa", "grano", "60 g en seco"], ["garbanzos cocidos", "legumbre", "120 g"], ["calabaza", "verde", "150 g"], ["calabacín", "verde", "½ ud"], ["rúcula", "verde", "50 g"], ["tahini", "grasa", "1 cda"], ["limón", "sabor", "½ ud"], ["ajo", "sabor", "1 diente"]],
    coccion: "Asar calabaza y calabacín 25 min a 200 °C; hervir la quinoa 15 min; montar el bowl y aliñar con tahini-limón-ajo.",
    tip: "Asa doble ración de verdura: mañana es otra comida resuelta." },
  { id: "m09", n: "Crema de lentejas rojas con cúrcuma", t: ["cen"], d: ["mind", "flex"], p: ["legumbre"], al: [],
    b: ["cerebro", "diabetes", "intestino"],
    ing: [["lentejas rojas", "legumbre", "70 g en seco"], ["zanahoria", "verde", "1 ud"], ["puerro", "sabor", "½ ud"], ["cúrcuma", "sabor", "1 cdta"], ["pimienta negra", "sabor", "al gusto"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Rehogar puerro y zanahoria, añadir lentejas, cúrcuma y agua; 20 min y batir hasta crema fina.",
    tip: "La lenteja roja no necesita remojo: cena de legumbre en 25 min." },

  /* ===== PLATOS PRINCIPALES — PESCADO ===== */
  { id: "m10", n: "Salmón al horno con boniato y brócoli", t: ["com", "cen"], d: ["mind", "dash"], p: ["pescado"], al: ["pescado"],
    b: ["cerebro", "corazon", "presion"],
    ing: [["salmón fresco", "prot", "150 g"], ["boniato", "verde", "1 ud"], ["brócoli", "verde", "150 g"], ["limón", "sabor", "½ ud"], ["eneldo", "sabor", "al gusto"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Boniato al horno 30 min a 200 °C; añadir salmón y brócoli los últimos 12-14 min. Terminar con limón y eneldo.",
    tip: "El plato MIND por excelencia: omega-3 + betacaroteno + crucífera." },
  { id: "m11", n: "Sardinas a la plancha con ensalada de tomate", t: ["com"], d: ["med"], p: ["pescado"], al: ["pescado"],
    b: ["corazon", "cerebro"],
    ing: [["sardinas frescas", "prot", "4-5 ud"], ["tomate", "verde", "2 ud"], ["cebolleta", "sabor", "½ ud"], ["orégano", "sabor", "al gusto"], ["aceite de oliva virgen extra", "grasa", "1 cda"], ["limón", "sabor", "½ ud"]],
    coccion: "Plancha muy caliente, 2-3 min por lado sin mover; ensalada aliñada con AOVE y orégano.",
    tip: "Pescado azul pequeño: máximo omega-3, mínimo mercurio y precio imbatible." },
  { id: "m12", n: "Merluza en papillote con verduras", t: ["cen"], d: ["med", "dash"], p: ["pescado"], al: ["pescado"],
    b: ["presion", "peso", "corazon"],
    ing: [["merluza en lomos", "prot", "150 g"], ["calabacín", "verde", "½ ud"], ["zanahoria", "verde", "1 ud"], ["puerro", "sabor", "½ ud"], ["limón", "sabor", "2 rodajas"], ["tomillo", "sabor", "1 ramita"], ["aceite de oliva virgen extra", "grasa", "1 cdta"]],
    coccion: "Paquete de papel de horno con verduras en juliana debajo, pescado encima, limón y tomillo; 14 min a 180 °C.",
    tip: "La técnica más limpia que existe: cero grasa extra y todo el jugo dentro." },
  { id: "m13", n: "Bacalao con pisto de verduras", t: ["com", "cen"], d: ["med"], p: ["pescado"], al: ["pescado"],
    b: ["corazon", "peso"],
    ing: [["bacalao fresco", "prot", "150 g"], ["tomate triturado", "despensa", "150 g"], ["pimiento rojo", "verde", "½ ud"], ["calabacín", "verde", "½ ud"], ["berenjena", "verde", "½ ud"], ["cebolla", "sabor", "½ ud"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Pisto lento (30 min) de todas las verduras en dados; posar el bacalao encima, tapar y cocinar 8 min en su vapor.",
    tip: "El pisto aguanta 4 días en nevera: hazlo en doble cantidad." },
  { id: "m14", n: "Dorada al horno con limón y verduras panadera", t: ["com"], d: ["med"], p: ["pescado"], al: ["pescado"],
    b: ["corazon"],
    ing: [["dorada", "prot", "1 ud (ración)"], ["patata", "verde", "1 ud"], ["cebolla", "sabor", "½ ud"], ["pimiento verde", "verde", "½ ud"], ["limón", "sabor", "½ ud"], ["romero", "sabor", "1 ramita"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Cama de patata y verdura en rodajas finas 25 min a 190 °C; dorada encima 15 min más con limón y romero.",
    tip: "Pide en la pescadería que te la limpien: cero trabajo en casa." },
  { id: "m15", n: "Trucha a la plancha con espinacas y pasas", t: ["cen"], d: ["mind"], p: ["pescado"], al: ["pescado", "frutos_secos"],
    b: ["cerebro", "corazon"],
    ing: [["trucha", "prot", "150 g"], ["espinacas", "verde", "200 g"], ["pasas", "fruta", "1 cda"], ["piñones o almendra laminada", "grasa", "1 cda"], ["ajo", "sabor", "1 diente"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Trucha a la plancha 3 min por lado; espinacas salteadas con ajo, pasas y piñones (estilo catalán).",
    tip: "Trucha: el omega-3 más económico después de la sardina." },
  { id: "m16", n: "Sepia a la plancha con ensalada verde y limón", t: ["cen"], d: ["med"], p: ["pescado"], al: ["pescado"],
    b: ["peso"],
    ing: [["sepia limpia", "prot", "200 g"], ["mezcla de hojas verdes", "verde", "100 g"], ["tomate cherry", "verde", "8 ud"], ["ajo", "sabor", "1 diente"], ["perejil", "sabor", "1 puñado"], ["aceite de oliva virgen extra", "grasa", "1 cda"], ["limón", "sabor", "½ ud"]],
    coccion: "Plancha muy fuerte 2-3 min por lado; terminar con majado de ajo, perejil, AOVE y limón.",
    tip: "Proteína altísima, grasa casi nula: la cena ligera definitiva." },
  { id: "m17", n: "Ceviche fácil de pescado blanco", t: ["cen"], d: ["flex"], p: ["pescado"], al: ["pescado"],
    b: ["peso"],
    ing: [["lubina o corvina muy fresca", "prot", "150 g"], ["lima", "sabor", "2 ud"], ["cebolla morada", "sabor", "¼ ud"], ["cilantro", "sabor", "1 puñado"], ["boniato cocido", "verde", "½ ud"], ["maíz dulce", "verde", "40 g"]],
    coccion: "Pescado en dados + zumo de lima 10-15 min en nevera; mezclar con cebolla y cilantro. Congela antes el pescado 48 h por seguridad.",
    tip: "Cocción por ácido: técnica de chef sin encender el fuego." },

  /* ===== PLATOS PRINCIPALES — AVE ===== */
  { id: "m18", n: "Pollo al limón con quinoa y brócoli al vapor", t: ["com"], d: ["dash"], p: ["ave"], al: [],
    b: ["presion", "peso"],
    ing: [["pechuga de pollo", "prot", "150 g"], ["quinoa", "grano", "60 g en seco"], ["brócoli", "verde", "200 g"], ["limón", "sabor", "1 ud"], ["ajo", "sabor", "1 diente"], ["tomillo", "sabor", "1 ramita"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Marinar el pollo 30 min en limón-ajo-tomillo; plancha 4-5 min por lado. Quinoa hervida 15 min, brócoli al vapor 6 min.",
    tip: "La marinada ácida hace el pollo jugoso y elimina la necesidad de sal." },
  { id: "m19", n: "Wok de pavo y verduras crujientes", t: ["cen"], d: ["flex"], p: ["ave"], al: [],
    b: ["peso"],
    ing: [["pechuga de pavo", "prot", "150 g"], ["pimiento rojo", "verde", "½ ud"], ["calabacín", "verde", "½ ud"], ["zanahoria", "verde", "1 ud"], ["jengibre", "sabor", "1 trozo"], ["salsa de soja baja en sal", "despensa", "1 cda"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Wok muy caliente: pavo en tiras 3 min, retirar; verduras en juliana 4 min; juntar con jengibre y soja 1 min.",
    tip: "Verdura al dente y colores vivos = nutrientes intactos." },
  { id: "m20", n: "Pollo al horno con cúrcuma y verduras de hoja", t: ["com"], d: ["mind"], p: ["ave"], al: [],
    b: ["cerebro"],
    ing: [["muslos de pollo sin piel", "prot", "2 ud"], ["cúrcuma", "sabor", "1 cdta"], ["pimienta negra", "sabor", "al gusto"], ["acelgas o kale", "verde", "200 g"], ["cebolla", "sabor", "½ ud"], ["boniato", "verde", "1 ud"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Untar el pollo con cúrcuma, pimienta y AOVE; horno 35 min a 200 °C con boniato y cebolla; saltear la hoja verde al final.",
    tip: "Muslo sin piel: más jugoso que la pechuga y sigue siendo magro." },
  { id: "m21", n: "Ensalada templada de pollo, espinaca y fresas", t: ["com", "cen"], d: ["mind", "flex"], p: ["ave"], al: ["frutos_secos"],
    b: ["cerebro", "peso"],
    ing: [["pechuga de pollo", "prot", "120 g"], ["espinacas frescas", "verde", "100 g"], ["fresas", "fruta", "80 g"], ["nueces", "grasa", "20 g"], ["vinagre balsámico", "sabor", "1 cdta"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Pollo a la plancha en tiras; montar sobre espinacas con fresas laminadas y nueces; aliñar templado.",
    tip: "Hoja verde + frutos rojos + nueces: triple ración MIND en un plato." },

  /* ===== PLATOS PRINCIPALES — HUEVO / VEGETARIANO ===== */
  { id: "m22", n: "Pisto de verduras con huevo a baja temperatura", t: ["cen"], d: ["med"], p: ["huevo"], al: ["huevo"],
    b: ["corazon", "peso"],
    ing: [["tomate triturado", "despensa", "200 g"], ["calabacín", "verde", "½ ud"], ["berenjena", "verde", "½ ud"], ["pimiento rojo", "verde", "½ ud"], ["cebolla", "sabor", "½ ud"], ["huevo", "prot", "1 ud"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Pisto a fuego lento 30 min; abrir un hueco, cascar el huevo, tapar y cuajar 4 min.",
    tip: "El sofrito lento de tomate + AOVE multiplica el licopeno disponible." },
  { id: "m23", n: "Tortilla de calabacín y cebolla con ensalada", t: ["cen"], d: ["med"], p: ["huevo"], al: ["huevo"],
    b: ["peso"],
    ing: [["huevos", "prot", "2 ud"], ["calabacín", "verde", "1 ud"], ["cebolla", "sabor", "½ ud"], ["mezcla de hojas verdes", "verde", "80 g"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Pochar calabacín y cebolla a fuego suave 10 min, escurrir, mezclar con huevo y cuajar por ambas caras.",
    tip: "Versión ligera de la tortilla española: el calabacín sustituye a la patata frita." },
  { id: "m24", n: "Pasta integral con pesto de nueces y tomatitos", t: ["com"], d: ["med", "flex"], p: ["veg"], al: ["gluten", "frutos_secos"],
    b: ["corazon", "cerebro"],
    ing: [["pasta integral", "grano", "70 g en seco"], ["albahaca fresca", "sabor", "1 manojo"], ["nueces", "grasa", "30 g"], ["ajo", "sabor", "½ diente"], ["tomate cherry", "verde", "10 ud"], ["aceite de oliva virgen extra", "grasa", "2 cda"], ["levadura nutricional o parmesano", "despensa", "1 cda"]],
    coccion: "Batir albahaca, nueces, ajo y AOVE; hervir la pasta al dente y mezclar fuera del fuego con el pesto y los cherry.",
    tip: "El pesto de nueces cambia piñones caros por omega-3 barato." },
  { id: "m25", n: "Arroz integral meloso de verduras y alcachofas", t: ["com"], d: ["med"], p: ["veg"], al: [],
    b: ["intestino", "diabetes"],
    ing: [["arroz integral", "grano", "70 g en seco"], ["alcachofas", "verde", "2 ud"], ["judía verde", "verde", "80 g"], ["tomate rallado", "verde", "1 ud"], ["ajo", "sabor", "2 dientes"], ["pimentón dulce", "sabor", "1 cdta"], ["azafrán", "sabor", "unas hebras"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Sofrito de ajo, tomate y pimentón; añadir verduras, arroz y caldo (3:1); 35-40 min a fuego medio.",
    tip: "El arroz integral pide más caldo y más tiempo que el blanco: paciencia." },
  { id: "m26", n: "Gazpacho + ensalada griega con feta", t: ["cen"], d: ["med"], p: ["lacteo"], al: ["lacteo"],
    b: ["presion", "corazon", "peso"],
    ing: [["tomate maduro", "verde", "3 ud"], ["pepino", "verde", "1 ud"], ["pimiento verde", "verde", "½ ud"], ["queso feta", "lacteo", "50 g"], ["aceitunas", "grasa", "8 ud"], ["cebolla morada", "sabor", "¼ ud"], ["aceite de oliva virgen extra", "grasa", "2 cda"], ["vinagre de Jerez", "sabor", "1 cda"], ["orégano", "sabor", "al gusto"]],
    coccion: "Gazpacho: batir tomate, ½ pepino, pimiento, vinagre y AOVE; colar y enfriar. Ensalada: resto de pepino, tomate, feta, aceitunas y orégano.",
    tip: "La cena de verano que hidrata, sacia y baja la presión a la vez." },
  { id: "m27", n: "Berenjenas rellenas de quinoa y verduras", t: ["com", "cen"], d: ["flex"], p: ["veg"], al: [],
    b: ["peso", "intestino"],
    ing: [["berenjena", "verde", "1 ud"], ["quinoa", "grano", "50 g en seco"], ["tomate triturado", "despensa", "100 g"], ["cebolla", "sabor", "½ ud"], ["ajo", "sabor", "1 diente"], ["comino", "sabor", "½ cdta"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Asar la berenjena 25 min, vaciar; saltear la carne con sofrito y quinoa cocida; rellenar y gratinar 8 min.",
    tip: "Funciona igual con calabacín o pimientos: técnica comodín." },

  /* ===== CARNE ROJA (máx. 1×/semana) ===== */
  { id: "m28", n: "Ternera magra a la plancha con pimientos asados", t: ["com"], d: ["med"], p: ["carne"], al: [],
    b: [],
    ing: [["filete de ternera magra", "prot", "125 g"], ["pimiento rojo", "verde", "1 ud"], ["mezcla de hojas verdes", "verde", "80 g"], ["ajo", "sabor", "1 diente"], ["romero", "sabor", "1 ramita"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Pimientos asados 30 min a 200 °C, pelar y aliñar con ajo; filete a la plancha fuerte, 2 min por cara, reposo 2 min.",
    tip: "Ración de carne roja: del tamaño de la palma de tu mano, una vez por semana." },

  /* ===== SNACKS ===== */
  { id: "s01", n: "Puñado de nueces + manzana", t: ["snk"], d: ["mind", "med"], p: ["veg"], al: ["frutos_secos"],
    b: ["cerebro", "colesterol"],
    ing: [["nueces", "grasa", "25 g"], ["manzana", "fruta", "1 ud"]],
    coccion: "Sin preparación.", tip: "El snack con más evidencia científica del mundo." },
  { id: "s02", n: "Yogur natural con canela", t: ["snk"], d: ["dash", "med"], p: ["lacteo"], al: ["lacteo"],
    b: ["intestino", "diabetes"],
    ing: [["yogur natural", "lacteo", "1 ud"], ["canela", "sabor", "1 pizca"]],
    coccion: "Sin preparación.", tip: "La canela aporta dulzor percibido sin azúcar." },
  { id: "s03", n: "Hummus con bastones de zanahoria y pepino", t: ["snk"], d: ["med", "flex"], p: ["legumbre"], al: [],
    b: ["diabetes", "peso", "intestino"],
    ing: [["hummus", "legumbre", "60 g"], ["zanahoria", "verde", "1 ud"], ["pepino", "verde", "½ ud"]],
    coccion: "Cortar bastones y mojar. Hummus casero: garbanzos + tahini + limón + comino, batidos.",
    tip: "Legumbre extra en el día sin sentarte a la mesa." },
  { id: "s04", n: "Fruta de temporada + 2 onzas de chocolate 85%", t: ["snk"], d: ["mind"], p: ["veg"], al: [],
    b: ["cerebro", "corazon"],
    ing: [["fruta de temporada", "fruta", "1 pieza"], ["chocolate ≥85%", "despensa", "20 g"]],
    coccion: "Sin preparación.", tip: "Los flavanoles del cacao puro son cardio y neuroprotectores." },
  { id: "s05", n: "Edamame con limón", t: ["snk"], d: ["flex"], p: ["legumbre"], al: [],
    b: ["peso", "colesterol"],
    ing: [["edamame", "legumbre", "100 g"], ["limón", "sabor", "¼ ud"]],
    coccion: "Hervir 4 min y aliñar con limón (y pimienta si quieres).",
    tip: "Proteína vegetal completa en formato picoteo." },
  { id: "s06", n: "Kéfir con arándanos", t: ["snk"], d: ["mind", "dash"], p: ["lacteo"], al: ["lacteo"],
    b: ["cerebro", "intestino"],
    ing: [["kéfir", "lacteo", "150 ml"], ["arándanos", "fruta", "60 g"]],
    coccion: "Sin preparación.", tip: "Probiótico + frutos rojos: eje intestino-cerebro en un vaso." },
  { id: "s07", n: "Almendras + mandarina", t: ["snk"], d: ["med", "dash"], p: ["veg"], al: ["frutos_secos"],
    b: ["corazon", "presion"],
    ing: [["almendras", "grasa", "20 g"], ["mandarina", "fruta", "2 ud"]],
    coccion: "Sin preparación.", tip: "Magnesio + vitamina C: la pareja anti-tensión." },
  { id: "s08", n: "Tostadita integral con tomate y AOVE", t: ["snk"], d: ["med"], p: ["veg"], al: ["gluten"],
    b: ["corazon"],
    ing: [["pan integral", "grano", "1 rebanada pequeña"], ["tomate", "verde", "½ ud"], ["aceite de oliva virgen extra", "grasa", "1 cdta"]],
    coccion: "Tostar, rallar, regar.", tip: "Merienda mediterránea de toda la vida." },

  /* ===== DESAYUNOS (ampliación) ===== */
  { id: "d11", n: "Gachas de trigo sarraceno con pera y canela", t: ["des"], d: ["flex", "dash"], p: ["veg"], al: [],
    b: ["diabetes", "colesterol"],
    ing: [["trigo sarraceno", "grano", "50 g"], ["pera", "fruta", "1 ud"], ["canela", "sabor", "1 pizca"], ["bebida vegetal sin azúcar", "despensa", "200 ml"], ["semillas de girasol", "grasa", "1 cda"]],
    coccion: "Cocer el trigo sarraceno 10-12 min en la bebida vegetal; coronar con pera en dados, canela y semillas.",
    tip: "Pseudocereal sin gluten con rutina, un flavonoide aliado de los capilares." },
  { id: "d12", n: "Yogur griego con granada y pistachos", t: ["des"], d: ["med", "mind"], p: ["lacteo"], al: ["lacteo", "frutos_secos"],
    b: ["corazon", "intestino"],
    ing: [["yogur griego natural", "lacteo", "150 g"], ["granada", "fruta", "½ ud"], ["pistachos", "grasa", "20 g"], ["miel", "despensa", "1 cdta"]],
    coccion: "Desgranar la granada golpeando la cáscara con una cuchara; montar en capas.",
    tip: "Los arilos de granada son de los antioxidantes más potentes de la frutería." },
  { id: "d13", n: "Tostada integral de hummus, pepino y sésamo", t: ["des"], d: ["flex", "med"], p: ["legumbre"], al: ["gluten"],
    b: ["diabetes", "peso"],
    ing: [["pan integral", "grano", "2 rebanadas"], ["hummus", "legumbre", "60 g"], ["pepino", "verde", "½ ud"], ["semillas de sésamo", "grasa", "1 cdta"], ["pimentón dulce", "sabor", "1 pizca"]],
    coccion: "Tostar, untar el hummus, cubrir con láminas finas de pepino y rematar con sésamo y pimentón.",
    tip: "Legumbre en el desayuno: saciedad estable hasta mediodía." },
  { id: "d14", n: "Bol de kéfir con mango y chía", t: ["des"], d: ["dash", "flex"], p: ["lacteo"], al: ["lacteo"],
    b: ["intestino", "presion"],
    ing: [["kéfir", "lacteo", "200 ml"], ["mango", "fruta", "½ ud"], ["semillas de chía", "grasa", "1 cda"], ["copos de avena", "grano", "2 cda"]],
    coccion: "Mezclar y dejar reposar 10 min para que la chía espese.",
    tip: "El mango aporta potasio y betacaroteno: pareja natural del kéfir." },
  { id: "d15", n: "Huevos al plato con tomate y pimentón (shakshuka exprés)", t: ["des"], d: ["med", "dash"], p: ["huevo"], al: ["huevo"],
    b: ["corazon", "peso"],
    ing: [["huevos", "prot", "2 ud"], ["tomate triturado", "despensa", "150 g"], ["pimiento rojo", "verde", "¼ ud"], ["cebolla", "sabor", "¼ ud"], ["pimentón ahumado", "sabor", "½ cdta"], ["comino", "sabor", "1 pizca"], ["aceite de oliva virgen extra", "grasa", "1 cdta"]],
    coccion: "Sofreír cebolla y pimiento 5 min, añadir tomate y especias 5 min; cascar los huevos encima, tapar y cuajar 4 min.",
    tip: "Desayuno salado de fin de semana: proteína + licopeno sin pan obligatorio." },
  { id: "d16", n: "Pan de centeno con requesón y arándanos", t: ["des"], d: ["mind", "dash"], p: ["lacteo"], al: ["gluten", "lacteo"],
    b: ["cerebro", "intestino"],
    ing: [["pan de centeno", "grano", "2 rebanadas"], ["requesón", "lacteo", "80 g"], ["arándanos", "fruta", "60 g"], ["miel", "despensa", "1 cdta"]],
    coccion: "Untar el requesón sobre el pan y coronar con los arándanos ligeramente chafados.",
    tip: "El centeno integral sacia más y tiene menor índice glucémico que el trigo." },
  { id: "d17", n: "Batido MIND de frutos rojos, avena y lino", t: ["des"], d: ["mind"], p: ["veg"], al: [],
    b: ["cerebro", "colesterol"],
    ing: [["frutos rojos (frescos o congelados)", "fruta", "100 g"], ["plátano", "fruta", "½ ud"], ["copos de avena", "grano", "2 cda"], ["lino molido", "grasa", "1 cda"], ["bebida vegetal sin azúcar", "despensa", "200 ml"]],
    coccion: "Batir todo 1 min hasta que quede cremoso.",
    tip: "Los frutos rojos congelados conservan intactos sus polifenoles y cuestan la mitad." },
  { id: "d18", n: "Tortitas de avena y plátano", t: ["des"], d: ["flex", "dash"], p: ["huevo"], al: ["huevo"],
    b: ["peso", "diabetes"],
    ing: [["copos de avena", "grano", "40 g"], ["plátano maduro", "fruta", "1 ud"], ["huevo", "prot", "1 ud"], ["canela", "sabor", "1 pizca"], ["aceite de oliva virgen extra", "grasa", "1 cdta"], ["fresas", "fruta", "60 g"]],
    coccion: "Batir avena, plátano, huevo y canela; cuajar tortitas pequeñas 2 min por cara a fuego medio; servir con fresas.",
    tip: "Tres ingredientes y cero azúcar añadido: el dulzor lo pone el plátano maduro." },
  { id: "d19", n: "Pudin de chía con kiwi y coco", t: ["des"], d: ["flex"], p: ["veg"], al: [],
    b: ["intestino", "peso"],
    ing: [["semillas de chía", "grasa", "2 cda"], ["bebida vegetal sin azúcar", "despensa", "150 ml"], ["kiwi", "fruta", "1 ud"], ["coco rallado", "grasa", "1 cdta"]],
    coccion: "Mezclar chía y bebida vegetal la noche anterior; por la mañana coronar con kiwi y coco.",
    tip: "Dos kiwis al día mejoran el tránsito intestinal según ensayos clínicos." },
  { id: "d20", n: "Tostada con sardinillas, tomate y orégano", t: ["des"], d: ["med"], p: ["pescado"], al: ["gluten", "pescado"],
    b: ["corazon", "cerebro"],
    ing: [["pan integral", "grano", "2 rebanadas"], ["sardinillas en AOVE", "prot", "1 lata pequeña"], ["tomate", "verde", "1 ud"], ["orégano", "sabor", "al gusto"]],
    coccion: "Tostar, rallar el tomate encima y colocar las sardinillas escurridas con orégano.",
    tip: "Desayuno nórdico-mediterráneo: omega-3 y calcio (las espinas se comen) a primera hora." },

  /* ===== MAINS (ampliación) — LEGUMBRE ===== */
  { id: "m29", n: "Potaje de garbanzos con acelgas y comino", t: ["com"], d: ["med", "dash"], p: ["legumbre"], al: [],
    b: ["presion", "colesterol", "intestino"],
    ing: [["garbanzos cocidos", "legumbre", "200 g"], ["acelgas", "verde", "150 g"], ["zanahoria", "verde", "1 ud"], ["cebolla", "sabor", "½ ud"], ["ajo", "sabor", "2 dientes"], ["comino", "sabor", "1 cdta"], ["pimentón dulce", "sabor", "1 cdta"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Sofrito de cebolla y ajo, añadir especias, garbanzos, acelgas troceadas y un vaso de caldo; guisar 15 min.",
    tip: "El potaje de viernes de toda la vida es un plato DASH casi perfecto." },
  { id: "m30", n: "Ensalada de lentejas con tomate, pepino y feta", t: ["com", "cen"], d: ["med", "flex"], p: ["legumbre"], al: ["lacteo"],
    b: ["diabetes", "peso"],
    ing: [["lentejas cocidas", "legumbre", "180 g"], ["tomate", "verde", "1 ud"], ["pepino", "verde", "½ ud"], ["queso feta", "lacteo", "40 g"], ["cebolla morada", "sabor", "¼ ud"], ["menta fresca", "sabor", "1 puñado"], ["aceite de oliva virgen extra", "grasa", "1 cda"], ["limón", "sabor", "½ ud"]],
    coccion: "Sin cocción: mezclar todo y aliñar con AOVE y limón. Mejor fría de nevera.",
    tip: "Lentejas cocidas y enfriadas: almidón resistente que alimenta tu microbiota." },
  { id: "m31", n: "Dahl de lentejas rojas con arroz basmati integral", t: ["com"], d: ["flex"], p: ["legumbre"], al: [],
    b: ["diabetes", "cerebro", "intestino"],
    ing: [["lentejas rojas", "legumbre", "80 g en seco"], ["arroz basmati integral", "grano", "60 g en seco"], ["tomate triturado", "despensa", "100 g"], ["cebolla", "sabor", "½ ud"], ["ajo", "sabor", "1 diente"], ["jengibre", "sabor", "1 trozo"], ["cúrcuma", "sabor", "1 cdta"], ["comino", "sabor", "1 cdta"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Sofreír cebolla, ajo y jengibre; añadir especias 30 s, lentejas, tomate y agua; 20 min a fuego suave. Servir con el arroz.",
    tip: "El plato nacional de la India vegetariana: proteína completa lenteja + arroz." },
  { id: "m32", n: "Judiones estofados con verduras y pimentón (fabada verde)", t: ["com"], d: ["med", "dash"], p: ["legumbre"], al: [],
    b: ["presion", "colesterol"],
    ing: [["judiones cocidos", "legumbre", "200 g"], ["puerro", "sabor", "1 ud"], ["zanahoria", "verde", "1 ud"], ["pimiento verde", "verde", "½ ud"], ["pimentón ahumado", "sabor", "1 cdta"], ["laurel", "sabor", "1 hoja"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Rehogar las verduras 8 min, añadir pimentón, judiones y caldo; guisar 15 min a fuego suave.",
    tip: "Todo el sabor de la fabada sin el embutido: el pimentón ahumado hace la magia." },
  { id: "m33", n: "Tacos de lentejas con pico de gallo", t: ["com", "cen"], d: ["flex"], p: ["legumbre"], al: [],
    b: ["peso", "corazon"],
    ing: [["lentejas cocidas", "legumbre", "150 g"], ["tortillas de maíz", "grano", "3 ud"], ["tomate", "verde", "1 ud"], ["cebolla morada", "sabor", "¼ ud"], ["cilantro", "sabor", "1 puñado"], ["lima", "sabor", "1 ud"], ["comino", "sabor", "1 cdta"], ["aguacate", "grasa", "½ ud"]],
    coccion: "Saltear las lentejas con comino 5 min; pico de gallo con tomate, cebolla, cilantro y lima; montar los tacos con aguacate.",
    tip: "La tortilla de maíz es integral y sin gluten por naturaleza." },
  { id: "m34", n: "Falafel al horno con ensalada y salsa tahini", t: ["com", "cen"], d: ["flex", "med"], p: ["legumbre"], al: [],
    b: ["peso", "diabetes"],
    ing: [["garbanzos cocidos", "legumbre", "200 g"], ["perejil y cilantro", "sabor", "1 manojo"], ["ajo", "sabor", "1 diente"], ["comino", "sabor", "1 cdta"], ["harina de garbanzo", "legumbre", "2 cda"], ["mezcla de hojas verdes", "verde", "100 g"], ["tomate", "verde", "1 ud"], ["tahini", "grasa", "1 cda"], ["limón", "sabor", "½ ud"]],
    coccion: "Triturar garbanzos con hierbas, ajo, comino y harina; formar bolitas y hornear 20 min a 200 °C girando a mitad. Servir sobre ensalada con tahini-limón.",
    tip: "Al horno en vez de frito: mismo crujiente, una fracción de la grasa." },
  { id: "m35", n: "Tempeh salteado con pak choi y sésamo", t: ["cen"], d: ["flex"], p: ["legumbre"], al: [],
    b: ["colesterol", "intestino"],
    ing: [["tempeh", "legumbre", "120 g"], ["pak choi", "verde", "200 g"], ["ajo", "sabor", "1 diente"], ["jengibre", "sabor", "1 trozo"], ["salsa de soja baja en sal", "despensa", "1 cda"], ["semillas de sésamo", "grasa", "1 cda"], ["aceite de oliva virgen extra", "grasa", "1 cdta"]],
    coccion: "Dorar el tempeh en láminas 3 min por cara; saltear el pak choi con ajo y jengibre 3 min; juntar con soja y sésamo.",
    tip: "El tempeh es soja fermentada: proteína completa + beneficios probióticos." },
  { id: "m36", n: "Bowl de garbanzos asados, boniato y kale", t: ["com", "cen"], d: ["flex", "mind"], p: ["legumbre"], al: [],
    b: ["cerebro", "intestino", "peso"],
    ing: [["garbanzos cocidos", "legumbre", "180 g"], ["boniato", "verde", "1 ud"], ["kale", "verde", "100 g"], ["pimentón ahumado", "sabor", "1 cdta"], ["comino", "sabor", "½ cdta"], ["aceite de oliva virgen extra", "grasa", "1 cda"], ["limón", "sabor", "½ ud"]],
    coccion: "Asar boniato en dados y garbanzos especiados 25 min a 200 °C; masajear el kale con AOVE y limón 1 min; montar el bowl.",
    tip: "Masajear el kale con aceite y ácido lo ablanda y quita el amargor." },
  { id: "m37", n: "Minestrone integral con alubias blancas", t: ["com", "cen"], d: ["med", "dash"], p: ["legumbre"], al: ["gluten"],
    b: ["presion", "peso", "intestino"],
    ing: [["alubias blancas cocidas", "legumbre", "150 g"], ["pasta integral corta", "grano", "40 g en seco"], ["tomate triturado", "despensa", "150 g"], ["zanahoria", "verde", "1 ud"], ["apio", "verde", "1 rama"], ["calabacín", "verde", "½ ud"], ["cebolla", "sabor", "½ ud"], ["albahaca fresca", "sabor", "1 puñado"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Sofrito de cebolla, zanahoria y apio; añadir tomate, caldo, alubias y calabacín 15 min; pasta los últimos 8 min; albahaca al servir.",
    tip: "La sopa que más verdura mete por cucharada: ideal para 'sumar vegetales' sin esfuerzo." },
  { id: "m38", n: "Guisantes salteados con huevo poché y menta", t: ["cen"], d: ["med", "flex"], p: ["legumbre", "huevo"], al: ["huevo"],
    b: ["peso", "diabetes"],
    ing: [["guisantes (frescos o congelados)", "legumbre", "200 g"], ["huevo", "prot", "1 ud"], ["cebolleta", "sabor", "1 ud"], ["menta fresca", "sabor", "1 puñado"], ["aceite de oliva virgen extra", "grasa", "1 cda"], ["limón", "sabor", "¼ ud"]],
    coccion: "Saltear cebolleta y guisantes 5 min; escalfar el huevo 3 min y ponerlo encima con menta picada y ralladura de limón.",
    tip: "El guisante congelado se congela a las horas de cosecharse: más fresco que el 'fresco'." },

  /* ===== MAINS (ampliación) — PESCADO ===== */
  { id: "m39", n: "Caballa a la plancha con ensalada de naranja e hinojo", t: ["com"], d: ["med", "mind"], p: ["pescado"], al: ["pescado"],
    b: ["corazon", "cerebro"],
    ing: [["caballa en filetes", "prot", "150 g"], ["naranja", "fruta", "1 ud"], ["hinojo", "verde", "½ bulbo"], ["cebolla morada", "sabor", "¼ ud"], ["aceitunas negras", "grasa", "8 ud"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Caballa a la plancha 3 min por lado; ensalada de naranja a rodajas, hinojo en láminas finas, cebolla y aceitunas.",
    tip: "La caballa iguala al salmón en omega-3 por una fracción del precio." },
  { id: "m40", n: "Salmón en papillote con espárragos y eneldo", t: ["cen"], d: ["mind", "dash"], p: ["pescado"], al: ["pescado"],
    b: ["cerebro", "presion"],
    ing: [["salmón fresco", "prot", "150 g"], ["espárragos verdes", "verde", "8 ud"], ["limón", "sabor", "3 rodajas"], ["eneldo", "sabor", "al gusto"], ["aceite de oliva virgen extra", "grasa", "1 cdta"]],
    coccion: "Paquete de papel de horno con espárragos debajo, salmón encima, limón y eneldo; 14 min a 180 °C.",
    tip: "El papillote se lleva al trabajo tal cual: se recalienta dentro de su propio paquete." },
  { id: "m41", n: "Boquerones al horno con pimientos asados", t: ["com"], d: ["med"], p: ["pescado"], al: ["pescado"],
    b: ["corazon"],
    ing: [["boquerones limpios", "prot", "200 g"], ["pimiento rojo", "verde", "1 ud"], ["ajo", "sabor", "2 dientes"], ["perejil", "sabor", "1 puñado"], ["limón", "sabor", "½ ud"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Pimientos asados 30 min a 200 °C; boquerones en fuente con ajo, perejil y AOVE, 8-10 min al horno.",
    tip: "Al horno en vez de fritos: todo el omega-3 del pescado azul pequeño sin rebozado." },
  { id: "m42", n: "Lubina al vapor con jengibre y cebolleta", t: ["cen"], d: ["flex", "dash"], p: ["pescado"], al: ["pescado"],
    b: ["presion", "peso"],
    ing: [["lubina en lomos", "prot", "150 g"], ["jengibre", "sabor", "1 trozo"], ["cebolleta", "sabor", "1 ud"], ["salsa de soja baja en sal", "despensa", "1 cda"], ["arroz integral", "grano", "60 g en seco"], ["pak choi", "verde", "150 g"]],
    coccion: "Vapor 8 min con jengibre en juliana encima; terminar con cebolleta y un cordón de soja caliente. Arroz y pak choi al vapor de acompañamiento.",
    tip: "Técnica cantonesa clásica: el pescado al vapor nunca queda seco." },
  { id: "m43", n: "Atún a la plancha con quinoa y verduras", t: ["com"], d: ["med"], p: ["pescado"], al: ["pescado"],
    b: ["corazon", "peso"],
    ing: [["atún fresco", "prot", "130 g"], ["quinoa", "grano", "60 g en seco"], ["calabacín", "verde", "½ ud"], ["pimiento rojo", "verde", "½ ud"], ["sésamo", "grasa", "1 cdta"], ["aceite de oliva virgen extra", "grasa", "1 cda"], ["limón", "sabor", "½ ud"]],
    coccion: "Atún vuelta y vuelta (1-2 min por cara, centro rosado); quinoa hervida y verduras a la plancha.",
    tip: "Atún fresco: 1 vez por semana como máximo por el mercurio; el resto, azul pequeño." },
  { id: "m44", n: "Guiso marinero de rape con patata y azafrán", t: ["com"], d: ["med"], p: ["pescado"], al: ["pescado"],
    b: ["corazon"],
    ing: [["rape en trozos", "prot", "150 g"], ["patata", "verde", "1 ud"], ["tomate triturado", "despensa", "100 g"], ["cebolla", "sabor", "½ ud"], ["ajo", "sabor", "2 dientes"], ["azafrán", "sabor", "unas hebras"], ["perejil", "sabor", "1 puñado"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Sofrito de cebolla, ajo y tomate; añadir patata en cachelos y caldo, 15 min; rape y azafrán los últimos 6 min.",
    tip: "'Cachelar' la patata (romperla en vez de cortarla) suelta almidón y liga el guiso solo." },
  { id: "m45", n: "Mejillones al vapor con limón y ensalada verde", t: ["cen"], d: ["med"], p: ["pescado"], al: ["pescado"],
    b: ["peso", "corazon"],
    ing: [["mejillones frescos", "prot", "400 g"], ["limón", "sabor", "1 ud"], ["ajo", "sabor", "1 diente"], ["perejil", "sabor", "1 puñado"], ["mezcla de hojas verdes", "verde", "100 g"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Abrir los mejillones al vapor 4-5 min con ajo (descartar los que no abran); regar con limón y perejil.",
    tip: "El marisco más sostenible, barato y rico en hierro y B12 que existe." },
  { id: "m46", n: "Poke bowl de salmón, arroz integral y edamame", t: ["com", "cen"], d: ["flex", "mind"], p: ["pescado"], al: ["pescado"],
    b: ["cerebro", "peso"],
    ing: [["salmón muy fresco (o marinado)", "prot", "120 g"], ["arroz integral", "grano", "60 g en seco"], ["edamame", "legumbre", "60 g"], ["pepino", "verde", "½ ud"], ["zanahoria", "verde", "1 ud"], ["aguacate", "grasa", "½ ud"], ["salsa de soja baja en sal", "despensa", "1 cda"], ["semillas de sésamo", "grasa", "1 cdta"]],
    coccion: "Marinar el salmón en dados con soja 10 min; montar sobre arroz con las verduras y el aguacate. Congela el pescado 48 h antes si va crudo.",
    tip: "El bowl que junta 5 esferas en un plato: grano, legumbre, pescado, verdura y grasa buena." },
  { id: "m47", n: "Bacalao al horno con ajo, pimentón y brócoli", t: ["cen"], d: ["med", "dash"], p: ["pescado"], al: ["pescado"],
    b: ["presion", "peso"],
    ing: [["bacalao fresco", "prot", "150 g"], ["brócoli", "verde", "200 g"], ["ajo", "sabor", "2 dientes"], ["pimentón dulce", "sabor", "1 cdta"], ["aceite de oliva virgen extra", "grasa", "1 cda"], ["limón", "sabor", "½ ud"]],
    coccion: "Horno 12 min a 190 °C con el brócoli alrededor; fuera del fuego, regar con AOVE infusionado con ajo laminado y pimentón.",
    tip: "El 'ajada' gallego sin freír el pescado: sabor máximo con técnica mínima." },
  { id: "m48", n: "Ensalada templada de alubias y sardinillas", t: ["cen"], d: ["med"], p: ["legumbre", "pescado"], al: ["pescado"],
    b: ["corazon", "colesterol"],
    ing: [["alubias blancas cocidas", "legumbre", "180 g"], ["sardinillas en AOVE", "prot", "1 lata"], ["tomate cherry", "verde", "8 ud"], ["rúcula", "verde", "50 g"], ["cebolla morada", "sabor", "¼ ud"], ["vinagre de Jerez", "sabor", "1 cdta"]],
    coccion: "Templar las alubias 1 min, mezclar con el resto y aliñar con el propio aceite de las sardinillas y vinagre.",
    tip: "Cena de despensa en 5 minutos: legumbre + pescado azul sin encender el fuego." },

  /* ===== MAINS (ampliación) — AVE ===== */
  { id: "m49", n: "Pavo al horno con manzana y cebolla", t: ["com"], d: ["dash", "flex"], p: ["ave"], al: [],
    b: ["presion", "peso"],
    ing: [["pechuga de pavo", "prot", "150 g"], ["manzana", "fruta", "1 ud"], ["cebolla", "sabor", "1 ud"], ["tomillo", "sabor", "1 ramita"], ["mezcla de hojas verdes", "verde", "80 g"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Cama de manzana y cebolla en rodajas, pavo encima con tomillo; 25 min a 190 °C. La fruta asada hace de salsa.",
    tip: "La manzana asada endulza el plato sin una cucharada de azúcar." },
  { id: "m50", n: "Pollo salteado con anacardos y pimiento", t: ["com"], d: ["flex"], p: ["ave"], al: ["frutos_secos"],
    b: ["corazon"],
    ing: [["pechuga de pollo", "prot", "130 g"], ["anacardos", "grasa", "25 g"], ["pimiento rojo", "verde", "½ ud"], ["pimiento verde", "verde", "½ ud"], ["jengibre", "sabor", "1 trozo"], ["salsa de soja baja en sal", "despensa", "1 cda"], ["arroz integral", "grano", "60 g en seco"]],
    coccion: "Wok fuerte: pollo en dados 3 min, retirar; pimientos 3 min; juntar con jengibre, soja y anacardos 1 min. Servir con arroz.",
    tip: "Tuesta los anacardos en seco 2 min antes: duplica su sabor." },
  { id: "m51", n: "Sopa de pollo, verduras y fideo integral", t: ["cen"], d: ["dash"], p: ["ave"], al: ["gluten"],
    b: ["presion", "peso"],
    ing: [["pechuga de pollo", "prot", "100 g"], ["fideo integral", "grano", "30 g en seco"], ["zanahoria", "verde", "1 ud"], ["apio", "verde", "1 rama"], ["puerro", "sabor", "½ ud"], ["laurel", "sabor", "1 hoja"], ["perejil", "sabor", "1 puñado"]],
    coccion: "Hervir el pollo con las verduras y laurel 20 min; desmigar, colar el caldo y cocer el fideo 5 min. Perejil al servir.",
    tip: "Caldo casero sin pastilla: todo el sabor, una fracción del sodio." },
  { id: "m52", n: "Brochetas de pollo marinado con yogur y especias", t: ["com"], d: ["med", "flex"], p: ["ave"], al: ["lacteo"],
    b: ["peso"],
    ing: [["pechuga de pollo", "prot", "150 g"], ["yogur natural", "lacteo", "60 g"], ["pimentón dulce", "sabor", "1 cdta"], ["comino", "sabor", "½ cdta"], ["ajo", "sabor", "1 diente"], ["limón", "sabor", "½ ud"], ["pimiento verde", "verde", "½ ud"], ["cebolla", "sabor", "½ ud"]],
    coccion: "Marinar el pollo en yogur especiado 30 min (o toda la noche); ensartar con verduras y plancha o horno 12-14 min girando.",
    tip: "El yogur ablanda la proteína por sus ácidos: técnica tandoori de manual." },
  { id: "m53", n: "Pollo a la cazadora (tomate, aceitunas y alcaparras)", t: ["com"], d: ["med"], p: ["ave"], al: [],
    b: ["corazon"],
    ing: [["muslos de pollo sin piel", "prot", "2 ud"], ["tomate triturado", "despensa", "200 g"], ["aceitunas", "grasa", "8 ud"], ["alcaparras", "sabor", "1 cda"], ["cebolla", "sabor", "½ ud"], ["ajo", "sabor", "1 diente"], ["romero", "sabor", "1 ramita"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Dorar el pollo, retirar; sofrito de cebolla y ajo, tomate 10 min; devolver el pollo con aceitunas y alcaparras, 20 min tapado.",
    tip: "Aceitunas y alcaparras aportan la sal justa: no añadas más." },
  { id: "m54", n: "Ensalada de pavo, aguacate y canónigos", t: ["cen"], d: ["flex", "mind"], p: ["ave"], al: [],
    b: ["cerebro", "peso"],
    ing: [["pechuga de pavo", "prot", "120 g"], ["canónigos", "verde", "80 g"], ["aguacate", "grasa", "½ ud"], ["tomate cherry", "verde", "8 ud"], ["pepino", "verde", "½ ud"], ["semillas de calabaza", "grasa", "1 cda"], ["aceite de oliva virgen extra", "grasa", "1 cda"], ["vinagre de manzana", "sabor", "1 cdta"]],
    coccion: "Pavo a la plancha en tiras; montar sobre los canónigos con el resto y aliñar.",
    tip: "Las semillas de calabaza son de las mejores fuentes vegetales de zinc y magnesio." },

  /* ===== MAINS (ampliación) — HUEVO / VEGETARIANO ===== */
  { id: "m55", n: "Crema de calabaza y zanahoria con semillas", t: ["cen"], d: ["dash", "flex"], p: ["veg"], al: [],
    b: ["presion", "peso", "intestino"],
    ing: [["calabaza", "verde", "250 g"], ["zanahoria", "verde", "1 ud"], ["puerro", "sabor", "½ ud"], ["jengibre", "sabor", "1 trozo"], ["semillas de calabaza", "grasa", "1 cda"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Rehogar puerro, añadir calabaza, zanahoria, jengibre y agua justa; 20 min y batir. Semillas tostadas por encima.",
    tip: "Añade un yogur o un huevo duro si es plato único: la crema sola se queda corta de proteína." },
  { id: "m56", n: "Espaguetis integrales al tomate con ajo y albahaca", t: ["com"], d: ["med"], p: ["veg"], al: ["gluten"],
    b: ["corazon", "intestino"],
    ing: [["espaguetis integrales", "grano", "70 g en seco"], ["tomate triturado", "despensa", "200 g"], ["ajo", "sabor", "2 dientes"], ["albahaca fresca", "sabor", "1 manojo"], ["guindilla", "sabor", "1 pizca"], ["aceite de oliva virgen extra", "grasa", "1½ cda"], ["levadura nutricional o parmesano", "despensa", "1 cda"]],
    coccion: "Dorar el ajo laminado en AOVE, añadir tomate 15 min a fuego suave; mezclar con la pasta al dente y albahaca rota a mano.",
    tip: "La marinara perfecta lleva 4 ingredientes: la calidad del tomate lo es todo." },
  { id: "m57", n: "Coliflor asada entera con tahini y granada", t: ["com", "cen"], d: ["flex", "mind"], p: ["veg"], al: [],
    b: ["cerebro", "intestino", "peso"],
    ing: [["coliflor", "verde", "½ ud"], ["tahini", "grasa", "2 cda"], ["limón", "sabor", "½ ud"], ["granada", "fruta", "¼ ud"], ["comino", "sabor", "1 cdta"], ["pimentón ahumado", "sabor", "½ cdta"], ["aceite de oliva virgen extra", "grasa", "1 cda"], ["garbanzos cocidos", "legumbre", "100 g"]],
    coccion: "Untar la coliflor con AOVE y especias; asar 35-40 min a 200 °C con los garbanzos alrededor; salsear con tahini-limón y granada.",
    tip: "Asada entera, la crucífera carameliza en vez de oler a hervido." },
  { id: "m58", n: "Revuelto de setas y espárragos trigueros", t: ["cen"], d: ["med"], p: ["huevo"], al: ["huevo"],
    b: ["peso", "intestino"],
    ing: [["huevos", "prot", "2 ud"], ["setas variadas", "verde", "150 g"], ["espárragos verdes", "verde", "6 ud"], ["ajo", "sabor", "1 diente"], ["perejil", "sabor", "1 puñado"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Saltear setas y espárragos troceados 5 min con ajo; añadir huevo batido fuera del fuego fuerte y cuajar cremoso.",
    tip: "Las setas son la única fuente vegetal natural de vitamina D (más si toman el sol 30 min)." },
  { id: "m59", n: "Ensalada caprese con aguacate y rúcula", t: ["cen"], d: ["med"], p: ["lacteo"], al: ["lacteo"],
    b: ["corazon", "peso"],
    ing: [["tomate maduro", "verde", "2 ud"], ["mozzarella fresca", "lacteo", "80 g"], ["aguacate", "grasa", "½ ud"], ["rúcula", "verde", "50 g"], ["albahaca fresca", "sabor", "1 puñado"], ["aceite de oliva virgen extra", "grasa", "1 cda"], ["vinagre balsámico", "sabor", "1 cdta"]],
    coccion: "Alternar rodajas de tomate, mozzarella y aguacate sobre la rúcula; albahaca, AOVE y balsámico por encima.",
    tip: "El trío tomate + grasa buena (AOVE y aguacate) maximiza la absorción del licopeno." },
  { id: "m60", n: "Sopa fría de remolacha y yogur", t: ["cen"], d: ["dash"], p: ["lacteo"], al: ["lacteo"],
    b: ["presion", "intestino"],
    ing: [["remolacha cocida", "verde", "200 g"], ["yogur natural", "lacteo", "125 g"], ["pepino", "verde", "½ ud"], ["eneldo", "sabor", "al gusto"], ["ajo", "sabor", "½ diente"], ["aceite de oliva virgen extra", "grasa", "1 cdta"]],
    coccion: "Batir remolacha, yogur, medio pepino y ajo; enfriar; servir con pepino en dados y eneldo.",
    tip: "Los nitratos de la remolacha bajan la presión arterial de forma medible en horas." },
  { id: "m61", n: "Bandeja de verduras asadas con huevo y za'atar", t: ["cen"], d: ["med", "flex"], p: ["huevo"], al: ["huevo"],
    b: ["peso", "intestino"],
    ing: [["calabacín", "verde", "½ ud"], ["berenjena", "verde", "½ ud"], ["pimiento rojo", "verde", "½ ud"], ["cebolla morada", "sabor", "½ ud"], ["huevos", "prot", "2 ud"], ["za'atar (o orégano y sésamo)", "sabor", "1 cdta"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Asar las verduras en dados 25 min a 200 °C; hacer dos huecos, cascar los huevos y hornear 6 min más; espolvorear za'atar.",
    tip: "Una sola bandeja, cero sartenes: la cena de horno que se limpia sola." },

  /* ===== CARNE ROJA (ampliación, máx. 1×/semana) ===== */
  { id: "m62", n: "Solomillo de cerdo con compota de manzana y col salteada", t: ["com"], d: ["med"], p: ["carne"], al: [],
    b: [],
    ing: [["solomillo de cerdo", "prot", "125 g"], ["manzana", "fruta", "1 ud"], ["col o repollo", "verde", "150 g"], ["cebolla", "sabor", "½ ud"], ["mostaza Dijon", "despensa", "1 cdta"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Sellar el solomillo y terminar al horno 12 min a 190 °C; compota rápida de manzana y cebolla; col salteada al dente con mostaza.",
    tip: "El solomillo de cerdo es tan magro como la pechuga de pollo: la excepción de la carne." },

  /* ===== MAINS — recetario mediterráneo validado (Fundación Dieta Mediterránea) ===== */
  { id: "m63", n: "Pasta con pesto trapanés (tomate y almendras)", t: ["com"], d: ["med"], p: ["veg"], al: ["gluten", "frutos_secos"],
    b: ["corazon", "colesterol"],
    ing: [["pasta tipo busiate o fusilli (integral)", "grano", "70 g en seco"], ["tomate maduro", "verde", "2 ud"], ["almendras crudas", "grasa", "25 g"], ["albahaca fresca", "sabor", "1 manojo"], ["ajo", "sabor", "1 diente"], ["aceite de oliva virgen extra", "grasa", "1½ cda"], ["pecorino o parmesano", "despensa", "1 cda"]],
    coccion: "Majar (o batir en pulsos) almendras, ajo, albahaca y tomate pelado con el AOVE hasta pesto granuloso; hervir la pasta al dente y mezclar fuera del fuego con el pesto en crudo y el queso.",
    tip: "El pesto siciliano de los marineros de Trapani: se sirve crudo, sin cocinar la salsa — máximo licopeno y vitamina C." },
  { id: "m64", n: "Bulgur con tomates y hierbabuena", t: ["com", "cen"], d: ["med", "flex"], p: ["veg"], al: ["gluten"],
    b: ["diabetes", "intestino", "colesterol"],
    ing: [["bulgur", "grano", "60 g en seco"], ["tomate maduro", "verde", "2 ud"], ["cebolla", "sabor", "½ ud"], ["hierbabuena o perejil", "sabor", "1 puñado"], ["limón", "sabor", "½ ud"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Sofreír la cebolla, añadir el tomate rallado 5 min, incorporar el bulgur y el doble de agua caliente; tapar y cocer 12-15 min a fuego suave. Terminar con hierbabuena y limón.",
    tip: "El bulgur ya viene precocido al vapor: es el grano integral más rápido de la despensa mediterránea." },
  { id: "m65", n: "Estofado de bacalao con alcachofas, pasas y piñones", t: ["com"], d: ["med"], p: ["pescado"], al: ["pescado", "frutos_secos"],
    b: ["corazon", "colesterol"],
    ing: [["bacalao en lomos", "prot", "150 g"], ["alcachofas", "verde", "2 ud"], ["tomate triturado", "despensa", "100 g"], ["cebolla", "sabor", "½ ud"], ["ajo", "sabor", "1 diente"], ["pasas", "fruta", "1 cda"], ["piñones", "grasa", "1 cda"], ["perejil", "sabor", "1 puñado"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Sofrito lento de cebolla, ajo y tomate; añadir las alcachofas en cuartos y un vaso de agua, 15 min; posar el bacalao con pasas y piñones encima y estofar tapado 8-10 min más.",
    tip: "Clásico catalán de Cuaresma: el dulzor de las pasas equilibra el punto salino del bacalao sin añadir sal." },

  /* ===== SNACKS (ampliación) ===== */
  { id: "s09", n: "Palomitas caseras con AOVE y pimentón", t: ["snk"], d: ["flex", "dash"], p: ["veg"], al: [],
    b: ["peso", "intestino"],
    ing: [["maíz para palomitas", "grano", "30 g"], ["aceite de oliva virgen extra", "grasa", "1 cdta"], ["pimentón ahumado", "sabor", "1 pizca"]],
    coccion: "Olla tapada a fuego medio-alto con el AOVE hasta que dejen de explotar; espolvorear pimentón.",
    tip: "Hechas en casa son grano integral: nada que ver con las de microondas con mantequilla." },
  { id: "s10", n: "Naranja + 2 onzas de chocolate 85%", t: ["snk"], d: ["mind", "med"], p: ["veg"], al: [],
    b: ["cerebro", "corazon"],
    ing: [["naranja", "fruta", "1 ud"], ["chocolate ≥85%", "despensa", "20 g"]],
    coccion: "Sin preparación.", tip: "Vitamina C + flavanoles: la merienda de invierno con más ciencia detrás." },
  { id: "s11", n: "Dip de yogur, pepino y menta con crudités", t: ["snk"], d: ["med", "dash"], p: ["lacteo"], al: ["lacteo"],
    b: ["presion", "peso"],
    ing: [["yogur griego natural", "lacteo", "100 g"], ["pepino", "verde", "¼ ud"], ["menta fresca", "sabor", "1 puñado"], ["zanahoria", "verde", "1 ud"], ["apio", "verde", "1 rama"]],
    coccion: "Rallar y escurrir el pepino, mezclar con yogur y menta; mojar los bastones.",
    tip: "Tzatziki exprés: probiótico + verdura cruda en 3 minutos." },
  { id: "s12", n: "Tortitas de arroz integral con guacamole rápido", t: ["snk"], d: ["flex"], p: ["veg"], al: [],
    b: ["corazon", "peso"],
    ing: [["tortitas de arroz integral", "grano", "2 ud"], ["aguacate", "grasa", "½ ud"], ["lima", "sabor", "¼ ud"], ["tomate", "verde", "½ ud"]],
    coccion: "Chafar el aguacate con lima, untar y coronar con tomate en daditos.",
    tip: "Grasa buena sobre grano ligero: sacia sin pesadez de media tarde." },
  { id: "s13", n: "Batido de kéfir y fresas", t: ["snk"], d: ["dash", "mind"], p: ["lacteo"], al: ["lacteo"],
    b: ["intestino", "cerebro"],
    ing: [["kéfir", "lacteo", "200 ml"], ["fresas", "fruta", "100 g"], ["canela", "sabor", "1 pizca"]],
    coccion: "Batir 30 segundos.", tip: "Merienda líquida post-entreno: proteína, probióticos y polifenoles." },
  { id: "s14", n: "Garbanzos crujientes al horno con especias", t: ["snk"], d: ["flex", "med"], p: ["legumbre"], al: [],
    b: ["diabetes", "colesterol", "intestino"],
    ing: [["garbanzos cocidos", "legumbre", "100 g"], ["pimentón ahumado", "sabor", "1 cdta"], ["comino", "sabor", "½ cdta"], ["aceite de oliva virgen extra", "grasa", "1 cdta"]],
    coccion: "Secar bien los garbanzos, especiar y hornear 30 min a 200 °C moviendo cada 10 min hasta que crujan.",
    tip: "El 'snack de bolsa' saludable: crujen como frutos secos y son legumbre." },
  { id: "s15", n: "Pera + puñado de avellanas", t: ["snk"], d: ["med", "mind"], p: ["veg"], al: ["frutos_secos"],
    b: ["colesterol", "corazon"],
    ing: [["pera", "fruta", "1 ud"], ["avellanas", "grasa", "20 g"]],
    coccion: "Sin preparación.", tip: "La avellana es la reina del ácido oleico entre los frutos secos, como el AOVE." },
  { id: "s16", n: "Apio con crema de cacahuete 100%", t: ["snk"], d: ["flex"], p: ["legumbre"], al: ["frutos_secos"],
    b: ["peso", "diabetes"],
    ing: [["apio", "verde", "2 ramas"], ["crema de cacahuete 100%", "grasa", "1 cda"]],
    coccion: "Rellenar los canales del apio con la crema.",
    tip: "Mira la etiqueta: 'ingredientes: cacahuetes'. Nada más." },
  { id: "s17", n: "Aceitunas + tomatitos cherry", t: ["snk"], d: ["med"], p: ["veg"], al: [],
    b: ["corazon"],
    ing: [["aceitunas", "grasa", "10 ud"], ["tomate cherry", "verde", "10 ud"], ["orégano", "sabor", "1 pizca"]],
    coccion: "Sin preparación.", tip: "El aperitivo mediterráneo original: enjuaga las aceitunas si vigilas el sodio." },
  { id: "s18", n: "Manzana asada con canela y nueces", t: ["snk"], d: ["mind", "dash"], p: ["veg"], al: ["frutos_secos"],
    b: ["cerebro", "diabetes", "intestino"],
    ing: [["manzana", "fruta", "1 ud"], ["canela", "sabor", "1 pizca"], ["nueces", "grasa", "15 g"]],
    coccion: "Descorazonar, espolvorear canela y hornear 20 min a 180 °C (o 4 min al microondas); nueces por encima.",
    tip: "Sabe a postre de pastelería y es fruta + fruto seco: el truco anti-antojo dulce." },
];

/* ---------------- COMBINACIONES GANADORAS ---------------- */
const COMBOS = [
  { t: "Lentejas + pimiento rojo o limón", que: "Vitamina C junto a legumbre", por: "La vitamina C convierte el hierro vegetal (no hemo) en su forma absorbible: multiplica su absorción hasta ×3. Por eso las lentejas siempre con ensalada de pimiento o un chorro de limón." },
  { t: "Tomate sofrito + aceite de oliva", que: "Licopeno cocinado en grasa buena", por: "El licopeno del tomate es liposoluble y se libera con calor: el sofrito lento en AOVE lo hace mucho más biodisponible que el tomate crudo. La base del sofrito mediterráneo es ciencia pura." },
  { t: "Cúrcuma + pimienta negra", que: "Curcumina con piperina", por: "La piperina de la pimienta aumenta la absorción de la curcumina hasta un 2000%. Sin pimienta, la cúrcuma apenas se absorbe. Añade también algo de grasa (AOVE) para rematar." },
  { t: "Ensalada + aguacate o AOVE", que: "Carotenoides con grasa", por: "Los carotenoides de zanahoria, tomate y hoja verde necesitan grasa para absorberse. Una ensalada sin aliño de grasa buena desperdicia gran parte de sus antioxidantes." },
  { t: "Avena + frutos rojos", que: "Beta-glucanos con polifenoles", por: "Los beta-glucanos de la avena reducen el colesterol LDL (evidencia EFSA) y los polifenoles de los frutos rojos protegen los vasos. El desayuno cardioprotector con más respaldo." },
  { t: "Yogur o kéfir + plátano y avena", que: "Probiótico + prebiótico = simbiótico", por: "Las bacterias vivas del fermentado (probiótico) se alimentan de la fibra del plátano y la avena (prebiótico). Juntos colonizan mejor el intestino que por separado." },
  { t: "Pescado azul + verdura de hoja", que: "Omega-3 con folato", por: "El DHA del pescado y el folato de la hoja verde actúan en sinergia sobre la función cognitiva: la combinación central de la dieta MIND (salmón con espinacas, sardinas con acelgas)." },
  { t: "Legumbre + cereal integral", que: "Proteína vegetal completa", por: "La legumbre es pobre en metionina y el cereal en lisina: juntos (lentejas con arroz, hummus con pan integral) forman proteína completa comparable a la animal. Sabiduría culinaria universal confirmada." },
  { t: "Ajo picado + 10 minutos de reposo", que: "Activar la alicina antes de cocinar", por: "La alicina (el compuesto cardioprotector del ajo) se forma al cortar y necesita ~10 min para desarrollarse. Si lo echas a la sartén recién picado, el calor la destruye antes de formarse." },
  { t: "Brócoli al vapor + mostaza o rúcula", que: "Rescatar el sulforafano", por: "El calor destruye la enzima que genera sulforafano (el anticancerígeno estrella de las crucíferas). La mostaza y la rúcula crudas aportan esa enzima de vuelta: añádelas al brócoli cocinado." },
  { t: "Huevo + verduras de hoja", que: "Luteína mejor absorbida", por: "La grasa de la yema aumenta varias veces la absorción de la luteína y zeaxantina de las espinacas (salud ocular y cognitiva). El revuelto de espinacas es más que la suma de sus partes." },
  { t: "Vinagre antes de un plato de carbohidratos", que: "Amortiguar la glucemia", por: "1-2 cucharadas de vinagre (en la ensalada de entrante) reducen el pico de glucosa de la comida posterior. Truco sencillo respaldado por varios ensayos clínicos." },
  { t: "Chocolate ≥85% + nueces", que: "Flavanoles con omega-3 vegetal", por: "Flavanoles del cacao (flujo sanguíneo cerebral) + ALA de las nueces (antiinflamatorio): el postre válido en la dieta MIND." },
  { t: "Sésamo/tahini + limón", que: "Calcio vegetal con vitamina C", por: "El tahini es de las mejores fuentes vegetales de calcio y el medio ácido mejora su solubilidad. La salsa tahini-limón clásica del hummus tiene su porqué." },
  { t: "Cocinar y enfriar el arroz o la patata", que: "Almidón resistente", por: "Al enfriar 24 h en nevera, parte del almidón se vuelve 'resistente': alimenta la microbiota y baja el impacto glucémico, incluso si luego lo recalientas. La ensalada de arroz de ayer es mejor que el arroz de hoy." },
];

/* ---------------- EQUIPAMIENTO MÍNIMO ---------------- */
const EQUIPO = [
  { n: "Cuchillo de chef (20 cm)", e: "🔪", esencial: true,
    uso: "El 90% de todos los cortes: verduras, proteínas, hierbas. Con este y la puntilla no necesitas ningún otro cuchillo.",
    tips: ["Afílalo con chaira cada semana: un cuchillo afilado es más seguro que uno romo.", "Nunca al lavavajillas: lavado a mano y secado inmediato.", "Garra con la mano libre: nudillos guían la hoja, dedos recogidos."] },
  { n: "Puntilla (9-10 cm)", e: "🗡️", esencial: true,
    uso: "Pelar, desvenar, tornear, retirar pieles de pescado, cortes de precisión que el cuchillo grande no alcanza.",
    tips: ["Ideal para fruta y para limpiar alcachofas.", "Es la pareja obligatoria del cuchillo de chef: juntos cubren todo."] },
  { n: "Tabla de corte grande (mín. 35×25 cm)", e: "🪵", esencial: true,
    uso: "Superficie de trabajo estable para todo. Grande de verdad: una tabla pequeña hace la cocina lenta y peligrosa.",
    tips: ["Paño húmedo debajo para que no baile.", "Si es de madera: aceite mineral una vez al mes.", "Ideal dos: una para vegetales, otra para proteína cruda."] },
  { n: "Sartén antiadherente 28 cm (apta para horno)", e: "🍳", esencial: true,
    uso: "Plancha, salteado, revuelto, tortilla, pescado, terminar platos al horno. La herramienta más usada de la cocina saludable.",
    tips: ["Fuego medio casi siempre: el antiadherente se degrada con calor extremo.", "Utensilios de silicona o madera, nunca metal.", "Si el mango es de metal, entra al horno: sartén = fuente de asar."] },
  { n: "Olla alta 4-6 L con tapa", e: "🍲", esencial: true,
    uso: "Legumbres, guisos, sopas, cremas, pasta, hervir verdura, caldos. El batch cooking del domingo vive aquí.",
    tips: ["Fondo grueso: reparte el calor y el sofrito no se quema.", "Guisa doble ración siempre: la legumbre congela perfecto."] },
  { n: "Cazo 16 cm", e: "🥘", esencial: true,
    uso: "Huevo escalfado, quinoa y arroz para 1-2 personas, salsas, recalentar, avena del desayuno.",
    tips: ["La medida justa para granos: 1 parte grano / 2 de agua, tapa y fuego mínimo."] },
  { n: "Bandeja de horno + papel de hornear", e: "♨️", esencial: true,
    uso: "Verduras asadas, pescado al horno, papillote, boniato, pollo. El horno es el cocinero que trabaja mientras tú no.",
    tips: ["200 °C es la temperatura comodín para asar verdura (25-30 min).", "Papillote: paquete bien cerrado de papel de horno, 14 min a 180 °C.", "Llena siempre la bandeja entera: lo asado de más es la comida de mañana."] },
  { n: "Batidora de mano con vaso picador", e: "🌀", esencial: true,
    uso: "Cremas de verduras, gazpacho, hummus, pestos, smoothies, salsas de yogur. Sustituye a robot, licuadora y picadora.",
    tips: ["Para hummus sedoso: bate el garbanzo aún templado con un cubito de hielo.", "El vaso picador hace el trabajo de la picadora de frutos secos y hierbas."] },
  { n: "Rallador fino tipo Microplane", e: "🧀", esencial: true,
    uso: "Ralladura de limón, ajo y jengibre al instante, tomate para tostadas, nuez moscada, poco queso que cunde mucho.",
    tips: ["El ajo rallado se integra en aliños sin trozos.", "La ralladura de cítrico es sabor gratis sin sal: úsala en todo."] },
  { n: "Colador / escurridor grande", e: "🕸️", esencial: true,
    uso: "Escurrir pasta, granos, legumbre de bote (¡enjuágala siempre!), lavar hoja verde y fruta.",
    tips: ["Enjuagar la legumbre de bote elimina hasta el 40% del sodio del líquido."] },
  { n: "Báscula de cocina + juego de cucharas medidoras", e: "⚖️", esencial: true,
    uso: "Raciones honestas de granos, frutos secos y aceite. Clave real en control de peso: el ojo siempre miente al alza.",
    tips: ["Pesa el grano en seco: 60-70 g por persona es la ración estándar.", "1 cda de AOVE = 10 g = 90 kcal: medirlo cambia el resultado."] },
  { n: "Tarros de vidrio herméticos (varios tamaños)", e: "🫙", esencial: true,
    uso: "Batch cooking, overnight oats, aliños agitados, conservar legumbre cocida, congelar raciones, transportar comidas.",
    tips: ["Vinagreta perfecta: todos los ingredientes al tarro y agitar 10 segundos.", "Deja 2 cm libres si congelas: el líquido expande."] },
  { n: "Vaporera plegable de acero", e: "🥦", esencial: false,
    uso: "Verdura y pescado al vapor dentro de tu propia olla: la técnica que más nutrientes conserva, sin comprar otro aparato.",
    tips: ["Brócoli: 5-6 min, verde brillante y al dente. Más tiempo = pierde la mitad de la gracia."] },
  { n: "Wok o sartén honda 30 cm", e: "🥢", esencial: false,
    uso: "Salteados a fuego fuerte de verduras, tofu y ave: mucha comida, poco aceite, 5 minutos.",
    tips: ["Todo cortado ANTES de encender el fuego: el wok no espera.", "Sartén bien caliente, ingredientes por tandas: si la llenas, hierve en vez de saltear."] },
  { n: "Olla a presión / exprés", e: "⏱️", esencial: false,
    uso: "Garbanzos en 20 min y alubias en 25 sin remojo largo: elimina la excusa número uno para no comer legumbre.",
    tips: ["Cocina legumbre para toda la semana el domingo y congela en tarros por raciones."] },
  { n: "Exprimidor de cítricos manual", e: "🍋", esencial: false,
    uso: "Limón y lima diarios para aliños, marinadas y agua con limón: en cocina saludable el ácido trabaja tanto como la sal.",
    tips: ["Rueda el limón presionando antes de cortarlo: suelta el doble de zumo."] },
];

/* ---------------- PLAN CLÍNICO: DIETA COLESTEROL 1800 kcal ----------------
   Fuente: hoja dietética del Institut Català de la Salut (ICS).
   Pesos netos, en crudo y sin desperdicios. Plan orientativo: no sustituye
   la pauta individualizada del equipo sanitario. ---------------- */
const DIETA_COLESTEROL = {
  titulo: "Dieta para el colesterol — 1800 kcal",
  fuente: "Institut Català de la Salut (hoja dietética clínica)",
  intro: "El exceso de colesterol en sangre favorece los depósitos de grasa en las arterias y es, junto al tabaco y la hipertensión, un factor decisivo del infarto de miocardio. Una alimentación adecuada es el primer paso de prevención y tratamiento.",
  recomendaciones: [
    "Menos grasas animales: carnes grasas (cerdo, cordero…) no más de 3 veces por semana.",
    "No más de 2 huevos a la semana (según esta pauta clínica).",
    "Leche y lácteos siempre descremados.",
    "Aceite de oliva para cocinar; en crudo vale cualquier aceite vegetal (oliva, girasol, soja, maíz). Nunca mantequilla ni manteca para cocinar.",
    "Evitar pastelería (ensaimadas, croissants, churros, pan de molde, helados cremosos) y precocinados/aperitivos (croquetas, canelones, cortezas).",
    "Pescado azul (sardina, boquerón, salmón, atún…) al menos 1 vez por semana; marisco con moderación.",
    "Más fibra: ensaladas y verdura, fruta entera, legumbres y productos integrales.",
    "Sal, especias, café e infusiones con moderación, salvo indicación contraria.",
    "El consumo de alcohol debe consultarse con el equipo sanitario.",
    "Aceite total del día: 3½ cucharadas soperas (35 cc) de aceite de oliva.",
  ],
  menu: [
    { comida: "Desayuno", items: ["200 cc de leche descremada — o 2 yogures naturales descremados", "40 g de pan — o 3 biscotes", "50 g de queso fresco — o 30 g de atún o sardinas"] },
    { comida: "Media mañana", items: ["50 g de pan — o 4 biscotes", "20 g de jamón york o del país (mejor: pescado azul u hortalizas)", "1 yogur natural descremado"] },
    { comida: "Comida", items: ["250 g de cualquier verdura", "200 g de patatas — o 60 g de arroz/pasta — o 80 g de pan — o 80 g de legumbres — o 240 g de guisantes/habas — o 360 g de maíz", "100 g de carne magra *", "20 g de pan — o 50 g de patatas — o 15 g de arroz/pasta — o 20 g de legumbres — o 1 biscote", "150 g de fruta **"] },
    { comida: "Merienda", items: ["50 g de pan — o 4 biscotes", "20 g de jamón york o del país (mejor: pescado azul u hortalizas)", "1 yogur natural descremado"] },
    { comida: "Cena", items: ["200 g de cualquier verdura", "150 g de patatas — o 45 g de arroz/pasta — o 60 g de pan — o 60 g de legumbres — o 180 g de guisantes/habas — o 270 g de maíz", "150 g de cualquier pescado *", "20 g de pan — o 50 g de patatas — o 15 g de arroz/pasta — o 20 g de legumbres — o 1 biscote", "150 g de fruta **"] },
  ],
  equivalencias: [
    { clave: "* 100 g de carne magra (ternera/buey) equivalen a", valores: ["¼ de pollo sin piel", "150 g de pescado blanco o azul", "80 g de jamón de york o del país", "80 g de legumbres"] },
    { clave: "** 150 g de fruta equivalen a", valores: ["150 g de manzana, pera, melocotón, albaricoque o ciruela", "200 g de naranja, mandarina, piña o fresas", "100 g de plátano, uva, higos o chirimoya", "350-400 g de melón o sandía"] },
  ],
  notas: [
    "En los bocadillos de desayuno, media mañana y merienda conviene sustituir el jamón/queso por pescado azul (atún, sardinas) u hortalizas (tomate, pimiento, berenjena) para variar sin subir el colesterol.",
    "La verdura puede sustituirse por una buena ensalada variada, una escalivada o un gazpacho ligero.",
    "Todas las cantidades son pesos netos, en crudo y sin desperdicios.",
    "Arroz y pasta triplican su peso al cocerse (30 g crudos ≈ 90-100 g cocidos); las legumbres lo duplican (40 g crudas ≈ 80-100 g cocidas).",
  ],
  medidas: [
    ["1 rebanada de pan de barra de ½ (2 cm)", "30-40 g"],
    ["1 rebanada de pan de barra de ¼ (2 cm)", "20-25 g"],
    ["1 vaso de agua o 1 taza de leche", "200 cc"],
    ["1 yogur comercial", "125 g"],
    ["1 cucharada sopera de aceite", "10 cc"],
    ["1 cucharada pequeña de aceite", "5 cc"],
    ["1 cucharada sopera de arroz o harina", "20-25 g"],
    ["1 puñado (mano cerrada) de arroz o pasta pequeña", "15 g"],
    ["1 taza de café de arroz o pasta pequeña", "20-25 g"],
    ["1 plato hondo de verdura (ración habitual)", "80-100 g"],
    ["1 pieza de fruta habitual", "200-300 g"],
    ["1 patata algo mayor que un huevo", "100 g"],
  ],
  notaApp: "Cómo encaja con esta app: marca «Colesterol alto» en tu perfil y el generador priorizará recetas con avena, legumbre, frutos secos y pescado azul, y eliminará la carne roja de tu semana — el mismo criterio de esta pauta clínica. Las recomendaciones actuales (AHA/OMS) son algo más flexibles con el huevo que esta hoja; ante dudas, manda lo que te diga tu equipo sanitario.",
};

/* ---------------- REGLAS SEMANALES (consenso de las 4 dietas) ---------------- */
const REGLAS = [
  { icono: "🥬", texto: "Verdura en comida y cena, hoja verde casi a diario (MIND: mín. 6/semana)" },
  { icono: "🫘", texto: "Legumbre 3-4 veces por semana como proteína principal" },
  { icono: "🐟", texto: "Pescado 2-3 veces por semana, al menos 1 azul (sardina, salmón, caballa)" },
  { icono: "🍓", texto: "Frutos rojos mínimo 2 veces por semana (MIND)" },
  { icono: "🥩", texto: "Carne roja máximo 1 vez por semana; procesada, casi nunca" },
  { icono: "🌰", texto: "Un puñado de frutos secos al día (nueces si el foco es el cerebro)" },
  { icono: "🫒", texto: "AOVE como grasa principal para cocinar y aliñar" },
  { icono: "🧂", texto: "Especias, hierbas y ácidos en lugar de sal (DASH: <2,3 g sodio/día)" },
  { icono: "🌾", texto: "Granos siempre integrales; fruta entera de postre, agua de bebida" },
];
