/* =========================================================
   Base de datos nutricional
   Dietas: med (Mediterránea), dash (DASH), flex (Flexitariana), mind (MIND)
   Beneficios: presion, corazon, diabetes, cerebro, peso, colesterol, intestino
   Proteína (p): pescado, ave, carne, legumbre, huevo, lacteo, veg
   Contiene (al): gluten, lacteo, pescado, huevo, frutos_secos
   Categorías de compra: verde, fruta, grano, legumbre, prot, lacteo, grasa, sabor, despensa
   Cantidades: por persona y ración
   ========================================================= */

const CATEGORIAS = {
  verde: { nombre: "🥬 Verduras y hortalizas", orden: 1 },
  fruta: { nombre: "🍎 Frutas", orden: 2 },
  grano: { nombre: "🌾 Granos integrales", orden: 3 },
  legumbre: { nombre: "🫘 Legumbres", orden: 4 },
  prot: { nombre: "🐟 Pescado, ave y huevos", orden: 5 },
  lacteo: { nombre: "🥛 Lácteos", orden: 6 },
  grasa: { nombre: "🥑 Grasas buenas y frutos secos", orden: 7 },
  sabor: { nombre: "🌿 Hierbas, especias y ácidos", orden: 8 },
  despensa: { nombre: "🏺 Despensa", orden: 9 },
};

const DIETAS = {
  med: { nombre: "Mediterránea", color: "#2e7d52" },
  dash: { nombre: "DASH", color: "#2563a8" },
  flex: { nombre: "Flexitariana", color: "#b0691c" },
  mind: { nombre: "MIND", color: "#7b4fa6" },
};

const BENEFICIOS = {
  presion: "Presión arterial",
  corazon: "Salud cardiovascular",
  diabetes: "Control glucémico",
  cerebro: "Salud cognitiva",
  peso: "Control de peso",
  colesterol: "Colesterol",
  intestino: "Salud intestinal",
};

/* ---------------- RECETAS ---------------- */
/* t: tipos de comida donde encaja — des, com, cen, snk */
const RECETAS = [
  /* ===== DESAYUNOS ===== */
  { id: "d01", n: "Porridge de avena con arándanos y nueces", t: ["des"], d: ["mind", "dash"], p: ["veg"], al: ["frutos_secos"],
    b: ["cerebro", "colesterol", "corazon"],
    ing: [["copos de avena", "grano", "50 g"], ["arándanos", "fruta", "80 g"], ["nueces", "grasa", "20 g"], ["canela", "sabor", "1 pizca"], ["bebida vegetal o leche", "lacteo", "200 ml"]],
    coccion: "Cocer la avena 5 min a fuego suave removiendo; coronar con arándanos, nueces y canela.",
    tip: "Usa avena certificada sin gluten si eres celíaco." },
  { id: "d02", n: "Yogur griego con fresas, chía y miel", t: ["des"], d: ["med", "dash"], p: ["lacteo"], al: ["lacteo"],
    b: ["intestino", "corazon"],
    ing: [["yogur griego natural", "lacteo", "150 g"], ["fresas", "fruta", "100 g"], ["semillas de chía", "grasa", "1 cda"], ["miel", "despensa", "1 cdta"]],
    coccion: "Sin cocción: montar en capas y dejar reposar 5 min para que la chía hidrate.",
    tip: "El yogur natural sin azúcar es el probiótico más barato que existe." },
  { id: "d03", n: "Tostada integral con tomate rallado y AOVE", t: ["des"], d: ["med"], p: ["veg"], al: ["gluten"],
    b: ["corazon", "presion"],
    ing: [["pan integral de masa madre", "grano", "2 rebanadas"], ["tomate maduro", "verde", "1 ud"], ["aceite de oliva virgen extra", "grasa", "1 cda"], ["orégano", "sabor", "al gusto"]],
    coccion: "Tostar el pan, rallar el tomate encima y regar con AOVE.",
    tip: "El desayuno más mediterráneo posible: licopeno + grasa buena." },
  { id: "d04", n: "Tostada de aguacate con huevo escalfado", t: ["des"], d: ["flex", "mind"], p: ["huevo"], al: ["gluten", "huevo"],
    b: ["cerebro", "peso"],
    ing: [["pan integral", "grano", "1 rebanada"], ["aguacate", "grasa", "½ ud"], ["huevo", "prot", "1 ud"], ["limón", "sabor", "unas gotas"], ["pimienta negra", "sabor", "al gusto"]],
    coccion: "Escalfar el huevo 3 min en agua con un chorrito de vinagre; chafar el aguacate con limón sobre la tostada.",
    tip: "Grasa insaturada + proteína = saciedad hasta la comida." },
  { id: "d05", n: "Revuelto de espinacas y champiñones", t: ["des"], d: ["mind", "flex"], p: ["huevo"], al: ["huevo"],
    b: ["cerebro", "peso"],
    ing: [["huevos", "prot", "2 ud"], ["espinacas frescas", "verde", "80 g"], ["champiñones", "verde", "80 g"], ["ajo", "sabor", "1 diente"], ["aceite de oliva virgen extra", "grasa", "1 cdta"]],
    coccion: "Saltear ajo, champiñón y espinaca 3 min; añadir huevo batido fuera del fuego fuerte, cuajar cremoso.",
    tip: "Hoja verde en el desayuno: la ración MIND más fácil de cumplir." },
  { id: "d06", n: "Kéfir con plátano, lino molido y canela", t: ["des"], d: ["dash", "med"], p: ["lacteo"], al: ["lacteo"],
    b: ["intestino", "presion"],
    ing: [["kéfir", "lacteo", "200 ml"], ["plátano", "fruta", "1 ud"], ["lino molido", "grasa", "1 cda"], ["canela", "sabor", "1 pizca"]],
    coccion: "Sin cocción: trocear el plátano y mezclar.",
    tip: "El potasio del plátano es aliado directo de la presión arterial (DASH)." },
  { id: "d07", n: "Overnight oats de manzana y canela", t: ["des"], d: ["dash", "flex"], p: ["veg"], al: [],
    b: ["colesterol", "diabetes"],
    ing: [["copos de avena", "grano", "50 g"], ["manzana", "fruta", "1 ud"], ["bebida vegetal sin azúcar", "despensa", "150 ml"], ["semillas de chía", "grasa", "1 cdta"], ["canela", "sabor", "1 pizca"]],
    coccion: "Mezclar todo la noche anterior con la manzana rallada; nevera y listo al despertar.",
    tip: "Los beta-glucanos de la avena reducen el colesterol LDL — evidencia sólida." },
  { id: "d08", n: "Tortilla francesa de hierbas con tomate aliñado", t: ["des"], d: ["med"], p: ["huevo"], al: ["huevo"],
    b: ["peso"],
    ing: [["huevos", "prot", "2 ud"], ["perejil y cebollino", "sabor", "1 puñado"], ["tomate", "verde", "1 ud"], ["aceite de oliva virgen extra", "grasa", "1 cdta"]],
    coccion: "Batir huevos con hierbas picadas, cuajar a fuego medio; tomate en gajos con AOVE y orégano.",
    tip: "Las hierbas frescas dan sabor sin una pizca de sal." },
  { id: "d09", n: "Smoothie verde de espinaca, plátano y kiwi", t: ["des"], d: ["flex", "mind"], p: ["veg"], al: [],
    b: ["cerebro", "intestino"],
    ing: [["espinacas frescas", "verde", "50 g"], ["plátano", "fruta", "1 ud"], ["kiwi", "fruta", "1 ud"], ["bebida vegetal sin azúcar", "despensa", "200 ml"], ["lino molido", "grasa", "1 cdta"]],
    coccion: "Batir todo 1 min. Beber al momento para no perder vitamina C.",
    tip: "Batido, no zumo: la fruta entera conserva toda su fibra." },
  { id: "d10", n: "Requesón con melocotón y almendras", t: ["des"], d: ["med", "dash"], p: ["lacteo"], al: ["lacteo", "frutos_secos"],
    b: ["presion", "peso"],
    ing: [["requesón", "lacteo", "150 g"], ["melocotón", "fruta", "1 ud"], ["almendras", "grasa", "15 g"], ["miel", "despensa", "1 cdta"]],
    coccion: "Sin cocción: montar y listo.",
    tip: "Proteína láctea + fruta: desayuno DASH de manual." },

  /* ===== PLATOS PRINCIPALES — LEGUMBRE ===== */
  { id: "m01", n: "Lentejas estofadas con verduras y pimentón", t: ["com"], d: ["med", "dash"], p: ["legumbre"], al: [],
    b: ["presion", "corazon", "diabetes", "colesterol"],
    ing: [["lentejas pardinas", "legumbre", "80 g en seco"], ["zanahoria", "verde", "1 ud"], ["cebolla", "sabor", "½ ud"], ["ajo", "sabor", "2 dientes"], ["tomate triturado", "despensa", "100 g"], ["pimentón dulce", "sabor", "1 cdta"], ["laurel", "sabor", "1 hoja"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Sofrito lento de cebolla, ajo y tomate 15 min; añadir lentejas, verduras, pimentón y agua; guisar 35-40 min a fuego suave.",
    tip: "Añade unas gotas de limón al servir: triplica la absorción del hierro." },
  { id: "m02", n: "Garbanzos con espinacas al comino", t: ["com", "cen"], d: ["med", "flex", "mind"], p: ["legumbre"], al: [],
    b: ["cerebro", "diabetes", "intestino"],
    ing: [["garbanzos cocidos", "legumbre", "200 g"], ["espinacas", "verde", "150 g"], ["ajo", "sabor", "2 dientes"], ["comino", "sabor", "1 cdta"], ["pimentón ahumado", "sabor", "½ cdta"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Dorar ajo laminado, añadir especias, garbanzos y espinacas; saltear 5 min hasta que la hoja caiga.",
    tip: "Plato andalusí clásico: legumbre + hoja verde en 10 minutos." },
  { id: "m03", n: "Curry de garbanzos con tomate y espinacas", t: ["com"], d: ["flex"], p: ["legumbre"], al: [],
    b: ["diabetes", "cerebro", "peso"],
    ing: [["garbanzos cocidos", "legumbre", "200 g"], ["tomate triturado", "despensa", "200 g"], ["espinacas", "verde", "100 g"], ["cebolla", "sabor", "½ ud"], ["cúrcuma", "sabor", "1 cdta"], ["jengibre", "sabor", "1 trozo"], ["pimienta negra", "sabor", "al gusto"], ["arroz integral", "grano", "60 g en seco"]],
    coccion: "Sofreír cebolla y jengibre, añadir especias 30 s, tomate 10 min, garbanzos y espinacas 5 min. Servir con arroz integral hervido.",
    tip: "La pimienta negra multiplica ×20 la absorción de la curcumina." },
  { id: "m04", n: "Ensalada de alubias blancas con atún y pimiento", t: ["com", "cen"], d: ["med"], p: ["legumbre", "pescado"], al: ["pescado"],
    b: ["corazon", "peso"],
    ing: [["alubias blancas cocidas", "legumbre", "180 g"], ["atún en conserva al natural", "prot", "80 g"], ["pimiento rojo", "verde", "½ ud"], ["cebolla morada", "sabor", "¼ ud"], ["perejil", "sabor", "1 puñado"], ["aceite de oliva virgen extra", "grasa", "1 cda"], ["vinagre de Jerez", "sabor", "1 cdta"]],
    coccion: "Sin cocción: mezclar y aliñar con vinagreta. Mejor tras 15 min de reposo.",
    tip: "Legumbre + pescado en un plato frío: cena de verano perfecta." },
  { id: "m05", n: "Chili de alubias rojas con arroz integral", t: ["com"], d: ["flex", "dash"], p: ["legumbre"], al: [],
    b: ["presion", "colesterol", "peso"],
    ing: [["alubias rojas cocidas", "legumbre", "200 g"], ["tomate triturado", "despensa", "200 g"], ["pimiento verde", "verde", "½ ud"], ["cebolla", "sabor", "½ ud"], ["maíz dulce", "verde", "50 g"], ["comino", "sabor", "1 cdta"], ["pimentón ahumado", "sabor", "1 cdta"], ["arroz integral", "grano", "60 g en seco"]],
    coccion: "Sofreír verduras, añadir especias, tomate y alubias; guisar 15 min. Servir sobre arroz integral.",
    tip: "Sin sal añadida: el ahumado del pimentón hace todo el trabajo (DASH)." },
  { id: "m06", n: "Salteado de tofu, brócoli y sésamo", t: ["cen"], d: ["flex"], p: ["legumbre"], al: [],
    b: ["peso", "corazon"],
    ing: [["tofu firme", "legumbre", "150 g"], ["brócoli", "verde", "200 g"], ["zanahoria", "verde", "1 ud"], ["ajo", "sabor", "1 diente"], ["jengibre", "sabor", "1 trozo"], ["semillas de sésamo", "grasa", "1 cda"], ["salsa de soja baja en sal", "despensa", "1 cda"]],
    coccion: "Wok a fuego fuerte: dorar el tofu en dados, retirar; saltear verduras 4 min, devolver el tofu, sazonar y sembrar sésamo.",
    tip: "Prensa el tofu 15 min antes: queda dorado, no aguado." },
  { id: "m07", n: "Hamburguesa de alubia negra con ensalada completa", t: ["com", "cen"], d: ["flex"], p: ["legumbre"], al: ["huevo"],
    b: ["peso", "corazon"],
    ing: [["alubias negras cocidas", "legumbre", "180 g"], ["copos de avena", "grano", "3 cda"], ["huevo", "prot", "1 ud"], ["comino", "sabor", "1 cdta"], ["mezcla de hojas verdes", "verde", "100 g"], ["tomate", "verde", "1 ud"], ["aguacate", "grasa", "½ ud"]],
    coccion: "Chafar alubias con avena, huevo y comino; formar y dorar 4 min por cara a la plancha. Acompañar de ensalada con aguacate.",
    tip: "La avena liga la hamburguesa sin pan rallado refinado." },
  { id: "m08", n: "Buddha bowl de quinoa, verduras asadas y tahini", t: ["com", "cen"], d: ["flex", "med"], p: ["legumbre"], al: [],
    b: ["intestino", "peso", "diabetes"],
    ing: [["quinoa", "grano", "60 g en seco"], ["garbanzos cocidos", "legumbre", "120 g"], ["calabaza", "verde", "150 g"], ["calabacín", "verde", "½ ud"], ["rúcula", "verde", "50 g"], ["tahini", "grasa", "1 cda"], ["limón", "sabor", "½ ud"], ["ajo", "sabor", "1 diente"]],
    coccion: "Asar calabaza y calabacín 25 min a 200 °C; hervir la quinoa 15 min; montar el bowl y aliñar con tahini-limón-ajo.",
    tip: "Asa doble ración de verdura: mañana es otra comida resuelta." },
  { id: "m09", n: "Crema de lentejas rojas con cúrcuma", t: ["cen"], d: ["mind", "flex"], p: ["legumbre"], al: [],
    b: ["cerebro", "diabetes", "intestino"],
    ing: [["lentejas rojas", "legumbre", "70 g en seco"], ["zanahoria", "verde", "1 ud"], ["puerro", "sabor", "½ ud"], ["cúrcuma", "sabor", "1 cdta"], ["pimienta negra", "sabor", "al gusto"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Rehogar puerro y zanahoria, añadir lentejas, cúrcuma y agua; 20 min y batir hasta crema fina.",
    tip: "La lenteja roja no necesita remojo: cena de legumbre en 25 min." },

  /* ===== PLATOS PRINCIPALES — PESCADO ===== */
  { id: "m10", n: "Salmón al horno con boniato y brócoli", t: ["com", "cen"], d: ["mind", "dash"], p: ["pescado"], al: ["pescado"],
    b: ["cerebro", "corazon", "presion"],
    ing: [["salmón fresco", "prot", "150 g"], ["boniato", "verde", "1 ud"], ["brócoli", "verde", "150 g"], ["limón", "sabor", "½ ud"], ["eneldo", "sabor", "al gusto"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Boniato al horno 30 min a 200 °C; añadir salmón y brócoli los últimos 12-14 min. Terminar con limón y eneldo.",
    tip: "El plato MIND por excelencia: omega-3 + betacaroteno + crucífera." },
  { id: "m11", n: "Sardinas a la plancha con ensalada de tomate", t: ["com"], d: ["med"], p: ["pescado"], al: ["pescado"],
    b: ["corazon", "cerebro"],
    ing: [["sardinas frescas", "prot", "4-5 ud"], ["tomate", "verde", "2 ud"], ["cebolleta", "sabor", "½ ud"], ["orégano", "sabor", "al gusto"], ["aceite de oliva virgen extra", "grasa", "1 cda"], ["limón", "sabor", "½ ud"]],
    coccion: "Plancha muy caliente, 2-3 min por lado sin mover; ensalada aliñada con AOVE y orégano.",
    tip: "Pescado azul pequeño: máximo omega-3, mínimo mercurio y precio imbatible." },
  { id: "m12", n: "Merluza en papillote con verduras", t: ["cen"], d: ["med", "dash"], p: ["pescado"], al: ["pescado"],
    b: ["presion", "peso", "corazon"],
    ing: [["merluza en lomos", "prot", "150 g"], ["calabacín", "verde", "½ ud"], ["zanahoria", "verde", "1 ud"], ["puerro", "sabor", "½ ud"], ["limón", "sabor", "2 rodajas"], ["tomillo", "sabor", "1 ramita"], ["aceite de oliva virgen extra", "grasa", "1 cdta"]],
    coccion: "Paquete de papel de horno con verduras en juliana debajo, pescado encima, limón y tomillo; 14 min a 180 °C.",
    tip: "La técnica más limpia que existe: cero grasa extra y todo el jugo dentro." },
  { id: "m13", n: "Bacalao con pisto de verduras", t: ["com", "cen"], d: ["med"], p: ["pescado"], al: ["pescado"],
    b: ["corazon", "peso"],
    ing: [["bacalao fresco", "prot", "150 g"], ["tomate triturado", "despensa", "150 g"], ["pimiento rojo", "verde", "½ ud"], ["calabacín", "verde", "½ ud"], ["berenjena", "verde", "½ ud"], ["cebolla", "sabor", "½ ud"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Pisto lento (30 min) de todas las verduras en dados; posar el bacalao encima, tapar y cocinar 8 min en su vapor.",
    tip: "El pisto aguanta 4 días en nevera: hazlo en doble cantidad." },
  { id: "m14", n: "Dorada al horno con limón y verduras panadera", t: ["com"], d: ["med"], p: ["pescado"], al: ["pescado"],
    b: ["corazon"],
    ing: [["dorada", "prot", "1 ud (ración)"], ["patata", "verde", "1 ud"], ["cebolla", "sabor", "½ ud"], ["pimiento verde", "verde", "½ ud"], ["limón", "sabor", "½ ud"], ["romero", "sabor", "1 ramita"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Cama de patata y verdura en rodajas finas 25 min a 190 °C; dorada encima 15 min más con limón y romero.",
    tip: "Pide en la pescadería que te la limpien: cero trabajo en casa." },
  { id: "m15", n: "Trucha a la plancha con espinacas y pasas", t: ["cen"], d: ["mind"], p: ["pescado"], al: ["pescado", "frutos_secos"],
    b: ["cerebro", "corazon"],
    ing: [["trucha", "prot", "150 g"], ["espinacas", "verde", "200 g"], ["pasas", "fruta", "1 cda"], ["piñones o almendra laminada", "grasa", "1 cda"], ["ajo", "sabor", "1 diente"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Trucha a la plancha 3 min por lado; espinacas salteadas con ajo, pasas y piñones (estilo catalán).",
    tip: "Trucha: el omega-3 más económico después de la sardina." },
  { id: "m16", n: "Sepia a la plancha con ensalada verde y limón", t: ["cen"], d: ["med"], p: ["pescado"], al: ["pescado"],
    b: ["peso"],
    ing: [["sepia limpia", "prot", "200 g"], ["mezcla de hojas verdes", "verde", "100 g"], ["tomate cherry", "verde", "8 ud"], ["ajo", "sabor", "1 diente"], ["perejil", "sabor", "1 puñado"], ["aceite de oliva virgen extra", "grasa", "1 cda"], ["limón", "sabor", "½ ud"]],
    coccion: "Plancha muy fuerte 2-3 min por lado; terminar con majado de ajo, perejil, AOVE y limón.",
    tip: "Proteína altísima, grasa casi nula: la cena ligera definitiva." },
  { id: "m17", n: "Ceviche fácil de pescado blanco", t: ["cen"], d: ["flex"], p: ["pescado"], al: ["pescado"],
    b: ["peso"],
    ing: [["lubina o corvina muy fresca", "prot", "150 g"], ["lima", "sabor", "2 ud"], ["cebolla morada", "sabor", "¼ ud"], ["cilantro", "sabor", "1 puñado"], ["boniato cocido", "verde", "½ ud"], ["maíz dulce", "verde", "40 g"]],
    coccion: "Pescado en dados + zumo de lima 10-15 min en nevera; mezclar con cebolla y cilantro. Congela antes el pescado 48 h por seguridad.",
    tip: "Cocción por ácido: técnica de chef sin encender el fuego." },

  /* ===== PLATOS PRINCIPALES — AVE ===== */
  { id: "m18", n: "Pollo al limón con quinoa y brócoli al vapor", t: ["com"], d: ["dash"], p: ["ave"], al: [],
    b: ["presion", "peso"],
    ing: [["pechuga de pollo", "prot", "150 g"], ["quinoa", "grano", "60 g en seco"], ["brócoli", "verde", "200 g"], ["limón", "sabor", "1 ud"], ["ajo", "sabor", "1 diente"], ["tomillo", "sabor", "1 ramita"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Marinar el pollo 30 min en limón-ajo-tomillo; plancha 4-5 min por lado. Quinoa hervida 15 min, brócoli al vapor 6 min.",
    tip: "La marinada ácida hace el pollo jugoso y elimina la necesidad de sal." },
  { id: "m19", n: "Wok de pavo y verduras crujientes", t: ["cen"], d: ["flex"], p: ["ave"], al: [],
    b: ["peso"],
    ing: [["pechuga de pavo", "prot", "150 g"], ["pimiento rojo", "verde", "½ ud"], ["calabacín", "verde", "½ ud"], ["zanahoria", "verde", "1 ud"], ["jengibre", "sabor", "1 trozo"], ["salsa de soja baja en sal", "despensa", "1 cda"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Wok muy caliente: pavo en tiras 3 min, retirar; verduras en juliana 4 min; juntar con jengibre y soja 1 min.",
    tip: "Verdura al dente y colores vivos = nutrientes intactos." },
  { id: "m20", n: "Pollo al horno con cúrcuma y verduras de hoja", t: ["com"], d: ["mind"], p: ["ave"], al: [],
    b: ["cerebro"],
    ing: [["muslos de pollo sin piel", "prot", "2 ud"], ["cúrcuma", "sabor", "1 cdta"], ["pimienta negra", "sabor", "al gusto"], ["acelgas o kale", "verde", "200 g"], ["cebolla", "sabor", "½ ud"], ["boniato", "verde", "1 ud"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Untar el pollo con cúrcuma, pimienta y AOVE; horno 35 min a 200 °C con boniato y cebolla; saltear la hoja verde al final.",
    tip: "Muslo sin piel: más jugoso que la pechuga y sigue siendo magro." },
  { id: "m21", n: "Ensalada templada de pollo, espinaca y fresas", t: ["com", "cen"], d: ["mind", "flex"], p: ["ave"], al: ["frutos_secos"],
    b: ["cerebro", "peso"],
    ing: [["pechuga de pollo", "prot", "120 g"], ["espinacas frescas", "verde", "100 g"], ["fresas", "fruta", "80 g"], ["nueces", "grasa", "20 g"], ["vinagre balsámico", "sabor", "1 cdta"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Pollo a la plancha en tiras; montar sobre espinacas con fresas laminadas y nueces; aliñar templado.",
    tip: "Hoja verde + frutos rojos + nueces: triple ración MIND en un plato." },

  /* ===== PLATOS PRINCIPALES — HUEVO / VEGETARIANO ===== */
  { id: "m22", n: "Pisto de verduras con huevo a baja temperatura", t: ["cen"], d: ["med"], p: ["huevo"], al: ["huevo"],
    b: ["corazon", "peso"],
    ing: [["tomate triturado", "despensa", "200 g"], ["calabacín", "verde", "½ ud"], ["berenjena", "verde", "½ ud"], ["pimiento rojo", "verde", "½ ud"], ["cebolla", "sabor", "½ ud"], ["huevo", "prot", "1 ud"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Pisto a fuego lento 30 min; abrir un hueco, cascar el huevo, tapar y cuajar 4 min.",
    tip: "El sofrito lento de tomate + AOVE multiplica el licopeno disponible." },
  { id: "m23", n: "Tortilla de calabacín y cebolla con ensalada", t: ["cen"], d: ["med"], p: ["huevo"], al: ["huevo"],
    b: ["peso"],
    ing: [["huevos", "prot", "2 ud"], ["calabacín", "verde", "1 ud"], ["cebolla", "sabor", "½ ud"], ["mezcla de hojas verdes", "verde", "80 g"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Pochar calabacín y cebolla a fuego suave 10 min, escurrir, mezclar con huevo y cuajar por ambas caras.",
    tip: "Versión ligera de la tortilla española: el calabacín sustituye a la patata frita." },
  { id: "m24", n: "Pasta integral con pesto de nueces y tomatitos", t: ["com"], d: ["med", "flex"], p: ["veg"], al: ["gluten", "frutos_secos"],
    b: ["corazon", "cerebro"],
    ing: [["pasta integral", "grano", "70 g en seco"], ["albahaca fresca", "sabor", "1 manojo"], ["nueces", "grasa", "30 g"], ["ajo", "sabor", "½ diente"], ["tomate cherry", "verde", "10 ud"], ["aceite de oliva virgen extra", "grasa", "2 cda"], ["levadura nutricional o parmesano", "despensa", "1 cda"]],
    coccion: "Batir albahaca, nueces, ajo y AOVE; hervir la pasta al dente y mezclar fuera del fuego con el pesto y los cherry.",
    tip: "El pesto de nueces cambia piñones caros por omega-3 barato." },
  { id: "m25", n: "Arroz integral meloso de verduras y alcachofas", t: ["com"], d: ["med"], p: ["veg"], al: [],
    b: ["intestino", "diabetes"],
    ing: [["arroz integral", "grano", "70 g en seco"], ["alcachofas", "verde", "2 ud"], ["judía verde", "verde", "80 g"], ["tomate rallado", "verde", "1 ud"], ["ajo", "sabor", "2 dientes"], ["pimentón dulce", "sabor", "1 cdta"], ["azafrán", "sabor", "unas hebras"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Sofrito de ajo, tomate y pimentón; añadir verduras, arroz y caldo (3:1); 35-40 min a fuego medio.",
    tip: "El arroz integral pide más caldo y más tiempo que el blanco: paciencia." },
  { id: "m26", n: "Gazpacho + ensalada griega con feta", t: ["cen"], d: ["med"], p: ["lacteo"], al: ["lacteo"],
    b: ["presion", "corazon", "peso"],
    ing: [["tomate maduro", "verde", "3 ud"], ["pepino", "verde", "1 ud"], ["pimiento verde", "verde", "½ ud"], ["queso feta", "lacteo", "50 g"], ["aceitunas", "grasa", "8 ud"], ["cebolla morada", "sabor", "¼ ud"], ["aceite de oliva virgen extra", "grasa", "2 cda"], ["vinagre de Jerez", "sabor", "1 cda"], ["orégano", "sabor", "al gusto"]],
    coccion: "Gazpacho: batir tomate, ½ pepino, pimiento, vinagre y AOVE; colar y enfriar. Ensalada: resto de pepino, tomate, feta, aceitunas y orégano.",
    tip: "La cena de verano que hidrata, sacia y baja la presión a la vez." },
  { id: "m27", n: "Berenjenas rellenas de quinoa y verduras", t: ["com", "cen"], d: ["flex"], p: ["veg"], al: [],
    b: ["peso", "intestino"],
    ing: [["berenjena", "verde", "1 ud"], ["quinoa", "grano", "50 g en seco"], ["tomate triturado", "despensa", "100 g"], ["cebolla", "sabor", "½ ud"], ["ajo", "sabor", "1 diente"], ["comino", "sabor", "½ cdta"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Asar la berenjena 25 min, vaciar; saltear la carne con sofrito y quinoa cocida; rellenar y gratinar 8 min.",
    tip: "Funciona igual con calabacín o pimientos: técnica comodín." },

  /* ===== CARNE ROJA (máx. 1×/semana) ===== */
  { id: "m28", n: "Ternera magra a la plancha con pimientos asados", t: ["com"], d: ["med"], p: ["carne"], al: [],
    b: [],
    ing: [["filete de ternera magra", "prot", "125 g"], ["pimiento rojo", "verde", "1 ud"], ["mezcla de hojas verdes", "verde", "80 g"], ["ajo", "sabor", "1 diente"], ["romero", "sabor", "1 ramita"], ["aceite de oliva virgen extra", "grasa", "1 cda"]],
    coccion: "Pimientos asados 30 min a 200 °C, pelar y aliñar con ajo; filete a la plancha fuerte, 2 min por cara, reposo 2 min.",
    tip: "Ración de carne roja: del tamaño de la palma de tu mano, una vez por semana." },

  /* ===== SNACKS ===== */
  { id: "s01", n: "Puñado de nueces + manzana", t: ["snk"], d: ["mind", "med"], p: ["veg"], al: ["frutos_secos"],
    b: ["cerebro", "colesterol"],
    ing: [["nueces", "grasa", "25 g"], ["manzana", "fruta", "1 ud"]],
    coccion: "Sin preparación.", tip: "El snack con más evidencia científica del mundo." },
  { id: "s02", n: "Yogur natural con canela", t: ["snk"], d: ["dash", "med"], p: ["lacteo"], al: ["lacteo"],
    b: ["intestino", "diabetes"],
    ing: [["yogur natural", "lacteo", "1 ud"], ["canela", "sabor", "1 pizca"]],
    coccion: "Sin preparación.", tip: "La canela aporta dulzor percibido sin azúcar." },
  { id: "s03", n: "Hummus con bastones de zanahoria y pepino", t: ["snk"], d: ["med", "flex"], p: ["legumbre"], al: [],
    b: ["diabetes", "peso", "intestino"],
    ing: [["hummus", "legumbre", "60 g"], ["zanahoria", "verde", "1 ud"], ["pepino", "verde", "½ ud"]],
    coccion: "Cortar bastones y mojar. Hummus casero: garbanzos + tahini + limón + comino, batidos.",
    tip: "Legumbre extra en el día sin sentarte a la mesa." },
  { id: "s04", n: "Fruta de temporada + 2 onzas de chocolate 85%", t: ["snk"], d: ["mind"], p: ["veg"], al: [],
    b: ["cerebro", "corazon"],
    ing: [["fruta de temporada", "fruta", "1 pieza"], ["chocolate ≥85%", "despensa", "20 g"]],
    coccion: "Sin preparación.", tip: "Los flavanoles del cacao puro son cardio y neuroprotectores." },
  { id: "s05", n: "Edamame con limón", t: ["snk"], d: ["flex"], p: ["legumbre"], al: [],
    b: ["peso", "colesterol"],
    ing: [["edamame", "legumbre", "100 g"], ["limón", "sabor", "¼ ud"]],
    coccion: "Hervir 4 min y aliñar con limón (y pimienta si quieres).",
    tip: "Proteína vegetal completa en formato picoteo." },
  { id: "s06", n: "Kéfir con arándanos", t: ["snk"], d: ["mind", "dash"], p: ["lacteo"], al: ["lacteo"],
    b: ["cerebro", "intestino"],
    ing: [["kéfir", "lacteo", "150 ml"], ["arándanos", "fruta", "60 g"]],
    coccion: "Sin preparación.", tip: "Probiótico + frutos rojos: eje intestino-cerebro en un vaso." },
  { id: "s07", n: "Almendras + mandarina", t: ["snk"], d: ["med", "dash"], p: ["veg"], al: ["frutos_secos"],
    b: ["corazon", "presion"],
    ing: [["almendras", "grasa", "20 g"], ["mandarina", "fruta", "2 ud"]],
    coccion: "Sin preparación.", tip: "Magnesio + vitamina C: la pareja anti-tensión." },
  { id: "s08", n: "Tostadita integral con tomate y AOVE", t: ["snk"], d: ["med"], p: ["veg"], al: ["gluten"],
    b: ["corazon"],
    ing: [["pan integral", "grano", "1 rebanada pequeña"], ["tomate", "verde", "½ ud"], ["aceite de oliva virgen extra", "grasa", "1 cdta"]],
    coccion: "Tostar, rallar, regar.", tip: "Merienda mediterránea de toda la vida." },
];

/* ---------------- COMBINACIONES GANADORAS ---------------- */
const COMBOS = [
  { t: "Lentejas + pimiento rojo o limón", que: "Vitamina C junto a legumbre", por: "La vitamina C convierte el hierro vegetal (no hemo) en su forma absorbible: multiplica su absorción hasta ×3. Por eso las lentejas siempre con ensalada de pimiento o un chorro de limón." },
  { t: "Tomate sofrito + aceite de oliva", que: "Licopeno cocinado en grasa buena", por: "El licopeno del tomate es liposoluble y se libera con calor: el sofrito lento en AOVE lo hace mucho más biodisponible que el tomate crudo. La base del sofrito mediterráneo es ciencia pura." },
  { t: "Cúrcuma + pimienta negra", que: "Curcumina con piperina", por: "La piperina de la pimienta aumenta la absorción de la curcumina hasta un 2000%. Sin pimienta, la cúrcuma apenas se absorbe. Añade también algo de grasa (AOVE) para rematar." },
  { t: "Ensalada + aguacate o AOVE", que: "Carotenoides con grasa", por: "Los carotenoides de zanahoria, tomate y hoja verde necesitan grasa para absorberse. Una ensalada sin aliño de grasa buena desperdicia gran parte de sus antioxidantes." },
  { t: "Avena + frutos rojos", que: "Beta-glucanos con polifenoles", por: "Los beta-glucanos de la avena reducen el colesterol LDL (evidencia EFSA) y los polifenoles de los frutos rojos protegen los vasos. El desayuno cardioprotector con más respaldo." },
  { t: "Yogur o kéfir + plátano y avena", que: "Probiótico + prebiótico = simbiótico", por: "Las bacterias vivas del fermentado (probiótico) se alimentan de la fibra del plátano y la avena (prebiótico). Juntos colonizan mejor el intestino que por separado." },
  { t: "Pescado azul + verdura de hoja", que: "Omega-3 con folato", por: "El DHA del pescado y el folato de la hoja verde actúan en sinergia sobre la función cognitiva: la combinación central de la dieta MIND (salmón con espinacas, sardinas con acelgas)." },
  { t: "Legumbre + cereal integral", que: "Proteína vegetal completa", por: "La legumbre es pobre en metionina y el cereal en lisina: juntos (lentejas con arroz, hummus con pan integral) forman proteína completa comparable a la animal. Sabiduría culinaria universal confirmada." },
  { t: "Ajo picado + 10 minutos de reposo", que: "Activar la alicina antes de cocinar", por: "La alicina (el compuesto cardioprotector del ajo) se forma al cortar y necesita ~10 min para desarrollarse. Si lo echas a la sartén recién picado, el calor la destruye antes de formarse." },
  { t: "Brócoli al vapor + mostaza o rúcula", que: "Rescatar el sulforafano", por: "El calor destruye la enzima que genera sulforafano (el anticancerígeno estrella de las crucíferas). La mostaza y la rúcula crudas aportan esa enzima de vuelta: añádelas al brócoli cocinado." },
  { t: "Huevo + verduras de hoja", que: "Luteína mejor absorbida", por: "La grasa de la yema aumenta varias veces la absorción de la luteína y zeaxantina de las espinacas (salud ocular y cognitiva). El revuelto de espinacas es más que la suma de sus partes." },
  { t: "Vinagre antes de un plato de carbohidratos", que: "Amortiguar la glucemia", por: "1-2 cucharadas de vinagre (en la ensalada de entrante) reducen el pico de glucosa de la comida posterior. Truco sencillo respaldado por varios ensayos clínicos." },
  { t: "Chocolate ≥85% + nueces", que: "Flavanoles con omega-3 vegetal", por: "Flavanoles del cacao (flujo sanguíneo cerebral) + ALA de las nueces (antiinflamatorio): el postre válido en la dieta MIND." },
  { t: "Sésamo/tahini + limón", que: "Calcio vegetal con vitamina C", por: "El tahini es de las mejores fuentes vegetales de calcio y el medio ácido mejora su solubilidad. La salsa tahini-limón clásica del hummus tiene su porqué." },
  { t: "Cocinar y enfriar el arroz o la patata", que: "Almidón resistente", por: "Al enfriar 24 h en nevera, parte del almidón se vuelve 'resistente': alimenta la microbiota y baja el impacto glucémico, incluso si luego lo recalientas. La ensalada de arroz de ayer es mejor que el arroz de hoy." },
];

/* ---------------- EQUIPAMIENTO MÍNIMO ---------------- */
const EQUIPO = [
  { n: "Cuchillo de chef (20 cm)", e: "🔪", esencial: true,
    uso: "El 90% de todos los cortes: verduras, proteínas, hierbas. Con este y la puntilla no necesitas ningún otro cuchillo.",
    tips: ["Afílalo con chaira cada semana: un cuchillo afilado es más seguro que uno romo.", "Nunca al lavavajillas: lavado a mano y secado inmediato.", "Garra con la mano libre: nudillos guían la hoja, dedos recogidos."] },
  { n: "Puntilla (9-10 cm)", e: "🗡️", esencial: true,
    uso: "Pelar, desvenar, tornear, retirar pieles de pescado, cortes de precisión que el cuchillo grande no alcanza.",
    tips: ["Ideal para fruta y para limpiar alcachofas.", "Es la pareja obligatoria del cuchillo de chef: juntos cubren todo."] },
  { n: "Tabla de corte grande (mín. 35×25 cm)", e: "🪵", esencial: true,
    uso: "Superficie de trabajo estable para todo. Grande de verdad: una tabla pequeña hace la cocina lenta y peligrosa.",
    tips: ["Paño húmedo debajo para que no baile.", "Si es de madera: aceite mineral una vez al mes.", "Ideal dos: una para vegetales, otra para proteína cruda."] },
  { n: "Sartén antiadherente 28 cm (apta para horno)", e: "🍳", esencial: true,
    uso: "Plancha, salteado, revuelto, tortilla, pescado, terminar platos al horno. La herramienta más usada de la cocina saludable.",
    tips: ["Fuego medio casi siempre: el antiadherente se degrada con calor extremo.", "Utensilios de silicona o madera, nunca metal.", "Si el mango es de metal, entra al horno: sartén = fuente de asar."] },
  { n: "Olla alta 4-6 L con tapa", e: "🍲", esencial: true,
    uso: "Legumbres, guisos, sopas, cremas, pasta, hervir verdura, caldos. El batch cooking del domingo vive aquí.",
    tips: ["Fondo grueso: reparte el calor y el sofrito no se quema.", "Guisa doble ración siempre: la legumbre congela perfecto."] },
  { n: "Cazo 16 cm", e: "🥘", esencial: true,
    uso: "Huevo escalfado, quinoa y arroz para 1-2 personas, salsas, recalentar, avena del desayuno.",
    tips: ["La medida justa para granos: 1 parte grano / 2 de agua, tapa y fuego mínimo."] },
  { n: "Bandeja de horno + papel de hornear", e: "♨️", esencial: true,
    uso: "Verduras asadas, pescado al horno, papillote, boniato, pollo. El horno es el cocinero que trabaja mientras tú no.",
    tips: ["200 °C es la temperatura comodín para asar verdura (25-30 min).", "Papillote: paquete bien cerrado de papel de horno, 14 min a 180 °C.", "Llena siempre la bandeja entera: lo asado de más es la comida de mañana."] },
  { n: "Batidora de mano con vaso picador", e: "🌀", esencial: true,
    uso: "Cremas de verduras, gazpacho, hummus, pestos, smoothies, salsas de yogur. Sustituye a robot, licuadora y picadora.",
    tips: ["Para hummus sedoso: bate el garbanzo aún templado con un cubito de hielo.", "El vaso picador hace el trabajo de la picadora de frutos secos y hierbas."] },
  { n: "Rallador fino tipo Microplane", e: "🧀", esencial: true,
    uso: "Ralladura de limón, ajo y jengibre al instante, tomate para tostadas, nuez moscada, poco queso que cunde mucho.",
    tips: ["El ajo rallado se integra en aliños sin trozos.", "La ralladura de cítrico es sabor gratis sin sal: úsala en todo."] },
  { n: "Colador / escurridor grande", e: "🕸️", esencial: true,
    uso: "Escurrir pasta, granos, legumbre de bote (¡enjuágala siempre!), lavar hoja verde y fruta.",
    tips: ["Enjuagar la legumbre de bote elimina hasta el 40% del sodio del líquido."] },
  { n: "Báscula de cocina + juego de cucharas medidoras", e: "⚖️", esencial: true,
    uso: "Raciones honestas de granos, frutos secos y aceite. Clave real en control de peso: el ojo siempre miente al alza.",
    tips: ["Pesa el grano en seco: 60-70 g por persona es la ración estándar.", "1 cda de AOVE = 10 g = 90 kcal: medirlo cambia el resultado."] },
  { n: "Tarros de vidrio herméticos (varios tamaños)", e: "🫙", esencial: true,
    uso: "Batch cooking, overnight oats, aliños agitados, conservar legumbre cocida, congelar raciones, transportar comidas.",
    tips: ["Vinagreta perfecta: todos los ingredientes al tarro y agitar 10 segundos.", "Deja 2 cm libres si congelas: el líquido expande."] },
  { n: "Vaporera plegable de acero", e: "🥦", esencial: false,
    uso: "Verdura y pescado al vapor dentro de tu propia olla: la técnica que más nutrientes conserva, sin comprar otro aparato.",
    tips: ["Brócoli: 5-6 min, verde brillante y al dente. Más tiempo = pierde la mitad de la gracia."] },
  { n: "Wok o sartén honda 30 cm", e: "🥢", esencial: false,
    uso: "Salteados a fuego fuerte de verduras, tofu y ave: mucha comida, poco aceite, 5 minutos.",
    tips: ["Todo cortado ANTES de encender el fuego: el wok no espera.", "Sartén bien caliente, ingredientes por tandas: si la llenas, hierve en vez de saltear."] },
  { n: "Olla a presión / exprés", e: "⏱️", esencial: false,
    uso: "Garbanzos en 20 min y alubias en 25 sin remojo largo: elimina la excusa número uno para no comer legumbre.",
    tips: ["Cocina legumbre para toda la semana el domingo y congela en tarros por raciones."] },
  { n: "Exprimidor de cítricos manual", e: "🍋", esencial: false,
    uso: "Limón y lima diarios para aliños, marinadas y agua con limón: en cocina saludable el ácido trabaja tanto como la sal.",
    tips: ["Rueda el limón presionando antes de cortarlo: suelta el doble de zumo."] },
];

/* ---------------- REGLAS SEMANALES (consenso de las 4 dietas) ---------------- */
const REGLAS = [
  { icono: "🥬", texto: "Verdura en comida y cena, hoja verde casi a diario (MIND: mín. 6/semana)" },
  { icono: "🫘", texto: "Legumbre 3-4 veces por semana como proteína principal" },
  { icono: "🐟", texto: "Pescado 2-3 veces por semana, al menos 1 azul (sardina, salmón, caballa)" },
  { icono: "🍓", texto: "Frutos rojos mínimo 2 veces por semana (MIND)" },
  { icono: "🥩", texto: "Carne roja máximo 1 vez por semana; procesada, casi nunca" },
  { icono: "🌰", texto: "Un puñado de frutos secos al día (nueces si el foco es el cerebro)" },
  { icono: "🫒", texto: "AOVE como grasa principal para cocinar y aliñar" },
  { icono: "🧂", texto: "Especias, hierbas y ácidos en lugar de sal (DASH: <2,3 g sodio/día)" },
  { icono: "🌾", texto: "Granos siempre integrales; fruta entera de postre, agua de bebida" },
];
